### ISSUE TITLE
Error when creating exchange

### ISSUE THREAD

**Issue by brianstorti** [rabbitmq/rabbitmq-delayed-message-exchange#102]
Hi,

I'm seeing this error when I try to create an exchange: 

```
=CRASH REPORT==== 6-Dec-2017::15:33:44 ===
  crasher:
    initial call: rabbit_channel:init/1
    pid: <0.677.0>
    registered_name: []
    exception exit: {function_clause,
                        [{rabbit_exchange_type_delayed_message,validate,
                             [{exchange,
                                  {resource,<<"/">>,exchange,
                                      <<"delayed_background_jobs">>},
                                  'x-delayed-message',true,false,false,
                                  [{<<"x-delayed-type">>,longstr,<<"topic">>}],
                                  undefined,undefined,
                                  {[],[]}}],
                             [{file,
                                  "src/rabbit_exchange_type_delayed_message.erl"},
                              {line,61}]},
                         {rabbit_exchange,declare,6,
                             [{file,"src/rabbit_exchange.erl"},{line,165}]},
                         {rabbit_channel,handle_method,3,
                             [{file,"src/rabbit_channel.erl"},{line,1234}]},
                         {rabbit_channel,handle_cast,2,
                             [{file,"src/rabbit_channel.erl"},{line,470}]},
                         {gen_server2,handle_msg,2,
                             [{file,"src/gen_server2.erl"},{line,1047}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,247}]}]}
      in function  gen_server2:terminate/3 (src/gen_server2.erl, line 1161)
    ancestors: [<0.674.0>,<0.673.0>,<0.668.0>,<0.667.0>,<0.347.0>,<0.346.0>,
                  <0.345.0>,rabbit_sup,<0.204.0>]
    message_queue_len: 0
    messages: []
    links: [<0.674.0>]
    dictionary: [{process_name,
                      {rabbit_channel,
                          {<<"127.0.0.1:53283 -> 127.0.0.1:5672">>,1}}},
                  {channel_operation_timeout,15000},
                  {{xtype_to_module,'x-delayed-message'},
                   rabbit_exchange_type_delayed_message},
                  {rand_seed,
                      {#{jump => #Fun<rand.16.15449617>,
                         max => 288230376151711743,
                         next => #Fun<rand.15.15449617>,type => exsplus},
                       [271804742252802042|232574223805928132]}},
                  {permission_cache,
                      [{{resource,<<"/">>,exchange,
                            <<"delayed_background_jobs">>},
                        configure}]}]
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 2081
  neighbours:

=SUPERVISOR REPORT==== 6-Dec-2017::15:33:44 ===
     Supervisor: {<0.674.0>,rabbit_channel_sup}
     Context:    child_terminated
     Reason:     {function_clause,
                     [{rabbit_exchange_type_delayed_message,validate,
                          [{exchange,
                               {resource,<<"/">>,exchange,
                                   <<"delayed_background_jobs">>},
                               'x-delayed-message',true,false,false,
                               [{<<"x-delayed-type">>,longstr,<<"topic">>}],
                               undefined,undefined,
                               {[],[]}}],
                          [{file,
                               "src/rabbit_exchange_type_delayed_message.erl"},
                           {line,61}]},
                      {rabbit_exchange,declare,6,
                          [{file,"src/rabbit_exchange.erl"},{line,165}]},
                      {rabbit_channel,handle_method,3,
                          [{file,"src/rabbit_channel.erl"},{line,1234}]},
                      {rabbit_channel,handle_cast,2,
                          [{file,"src/rabbit_channel.erl"},{line,470}]},
                      {gen_server2,handle_msg,2,
                          [{file,"src/gen_server2.erl"},{line,1047}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.677.0>},
                  {name,channel},
                  {mfargs,
                      {rabbit_channel,start_link,
                          [1,<0.669.0>,<0.675.0>,<0.669.0>,
                           <<"127.0.0.1:53283 -> 127.0.0.1:5672">>,
                           rabbit_framing_amqp_0_9_1,
                           {user,<<"guest">>,
                               [administrator],
                               [{rabbit_auth_backend_internal,none}]},
                           <<"/">>,
                           [{<<"publisher_confirms">>,bool,true},
                            {<<"consumer_cancel_notify">>,bool,true},
                            {<<"exchange_exchange_bindings">>,bool,true},
                            {<<"basic.nack">>,bool,true},
                            {<<"connection.blocked">>,bool,true},
                            {<<"authentication_failure_close">>,bool,true}],
                           <0.670.0>,<0.676.0>]}},
                  {restart_type,intrinsic},
                  {shutdown,70000},
                  {child_type,worker}]
```

Seems to be working fine with RabbitMQ 3.6.14 and Erlang 19.3, but fails with Erlang 20.1.7. Any ideas?

Thank you!

**Comment by lukebakken** [comment]
Hi Brian -

Without a means to reproduce this there isn't much we can do with this report. Can you provide the code or other method you're using to declare this exchange?

I can see that [this line](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/blob/master/src/rabbit_exchange_type_delayed_message.erl#L61), given the data provided, is what is triggering the error. It looks as though an incompatible `exchange` record is being used. Did you recently upgrade from a previous RabbitMQ version? Did anything else in your environment change?

**Comment by brianstorti** [comment]
I can reproduce it by trying to create an exchange through the RabbitMQ Management plugin. Alternatively, if you have Ruby installed you can also reproduce it with:

```
gem install bunny && \
  ruby -e 'require "bunny"; Bunny::Exchange.new(Bunny.new.start.create_channel, "x-delayed-message", "exchange-name", durable: true, arguments: { "x-delayed-type" => :topic })'
```

And just to confirm that a normal `topic` exchange works fine:
```
ruby -e 'require "bunny"; Bunny::Exchange.new(Bunny.new.start.create_channel, "topic", "exchange-name", durable: true, arguments: {})'
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
We don't have any RabbitMQ or plugin details, only the Erlang version. This is mailing list material.

**Comment by michaelklishin** [comment]
If you search GitHub issues for `function_clause`, at least in some cases the Erlang version used was too old. 20.1.x is not too old, obviously, but this plugin hasn't changed since OTP 20 was released, so chances are it is a compatibility/version mismatch problem and therefore we need all details.

**Comment by lukebakken** [comment]
@brianstorti @michaelklishin - Here's what I did to reproduce this:

* Downloaded the `rabbitmq-delayed-message-exchange` plugin from [here](http://www.rabbitmq.com/community-plugins.html)
* Installed it - note the plugin versions (output is truncated) -
```
$ ./sbin/rabbitmq-plugins list
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status:   [failed to contact rabbit@shostakovich - status not shown]
 |/
[e ] amqp_client                       3.6.14
...
[E ] rabbitmq_delayed_message_exchange 3.7.0-rc.2
...
[  ] rabbitmq_event_exchange           3.6.14
```
* Reproduced the issue with @brianstorti 's ruby code (thanks!)

So, I suspect it has something to do with the community plugins on the download page vs RabbitMQ version. @brianstorti - please run `rabbitmq-plugins list` to see what plugin version you have installed.

**Comment by michaelklishin** [comment]
So it's a 3.7.0 plugin running on a 3.6.14 node. Can the same be reproduced with matching versions of 3.6.14? Matching versions of 3.7.0?

**Comment by michaelklishin** [comment]
One issue I can confirm is that the [Community Plugins page](http://www.rabbitmq.com/community-plugins.html) only has a 3.7.0 download link and does not link to a 3.6 version.

**Comment by brianstorti** [comment]
@lukebakken Yeah, I have the same version installed (downloaded from the community plugins page): 

`[E*] rabbitmq_delayed_message_exchange 3.7.0-rc.2`

Where can I get the 3.6 version from?

Thanks for your help.

**Comment by lukebakken** [comment]
@brianstorti - you can fix this issue by compiling this plugin yourself. I have verified that this process works. You must have erlang in your `PATH` and be sure to check out the `rabbitmq_v3_6_14` tag first:

```
git clone https://rabbitmq/rabbitmq-delayed-message-exchange.git
cd rabbitmq-delayed-message-exchange
git checkout rabbitmq_v3_16_14
make dist
```

Or, you can download it from [here](https://goo.gl/Vgp1tu).

**Comment by michaelklishin** [comment]
There is a 3.6 version available [from Bintray](https://bintray.com/rabbitmq/community-plugins/rabbitmq_delayed_message_exchange/v3.6.x).

Another issue I see is that Community Plugins links to an RC version even though there is a [final one](https://bintray.com/rabbitmq/community-plugins/rabbitmq_delayed_message_exchange/3.7.0).

I will correct the site.

**Comment by brianstorti** [comment]
That worked, thank you guys.

**Comment by michaelklishin** [comment]
The site portion of this is addressed in https://github.com/rabbitmq/rabbitmq-website/commit/f7f86979e252d7054bbe16e129e7f7d4655202eb and should be live in minutes. Thanks for bringing this up, @brianstorti.
