### ISSUE TITLE
Is there a case of using this plug-in to stop the rabbitmq service

### ISSUE THREAD

**Issue by bluexzh** [rabbitmq/rabbitmq-delayed-message-exchange#103]
I am a Chinese user, we use this plug-in a delay of 15 minutes, 15 minutes of news more than a million, sometimes found that when the memory exceeds the warning value, if memory have not been released, we have to crash the rabbitmq service. I see some people here mentioned that the plug-in does not recommend dealing with the business at a million levels, and does not know whether it is related to this.

**Comment by lukebakken** [comment]
Hello!

The RabbitMQ team does not use GitHub issues for discussion. Please post this message to the [`rabbitmq-users` mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users).

**Comment by michaelklishin** [comment]
There is a limitations section in the README.
