### ISSUE TITLE
Crashing after upgrading Erlang and RabbitMQ

### ISSUE THREAD

**Issue by kolbeywgl** [rabbitmq/rabbitmq-delayed-message-exchange#111]
#**We upgraded to:**
Erlang version | 20.1
RabbitMQ version | 3.7.4 |  

Now we get these errors very intermittently (about a dozen a day). The messages seems to lost during this.

`
2018-05-18 05:35:06.838 [error] <0.10766.778> CRASH REPORT Process <0.10766.778> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(rabbit_delayed_message, {delay_message,{exchange,{resource,<<"arhpnyss">>,exchange,<<"schedule">>},'x-delayed-message',true,...},...}, infinity) in gen_server:call/3 line 214 in gen_server2:terminate/3 line 1166
`

`Connection closed: 541 (INTERNAL-ERROR) with message \"INTERNAL_ERROR\"`

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
An Erlang process responsible for "delaying" messages isn't running. We don't have enough information to suggest why. It is then restarted and subsequent requests succeed.

Please share a way to reproduce and your logs on rabbitmq-users.

**Comment by Zwierzu** [comment]
We experienced the similar issue after rabbitmq upgrate to latest version. A simple procedure helped:
- disable delay plugin (rabbitmq-plugins disable rabbitmq_delayed_message_exchange)
- enable delay plugin (rabbitmq-plugins enable rabbitmq_delayed_message_exchange)
Hope this helps.
