### ISSUE TITLE
rabbitmq_delayed_message_exchange

### ISSUE THREAD

**Issue by phcsea** [rabbitmq/rabbitmq-delayed-message-exchange#117]
How to download plugin rabbitmq_delayed_message_exchange
I can't download it from this url: https://dl.bintray.com/rabbitmq/community-plugins/3.7.x/rabbitmq_delayed_message_exchange/rabbitmq_delayed_message_exchange-20171201-3.7.x.zip

**Comment by michaelklishin** [comment]
Bintray rate limited our org again. We've contacted support.

**Comment by justbenya** [comment]
Hello! This link doesn't work (Forbidden): https://dl.bintray.com/rabbitmq/community-plugins/3.7.x/rabbitmq_delayed_message_exchange/rabbitmq_delayed_message_exchange-20171201-3.7.x.zip
