### ISSUE TITLE
RabbitMQ 3.7.10 plugins_not_found

### ISSUE THREAD

**Issue by cuongsimplypost** [rabbitmq/rabbitmq-delayed-message-exchange#119]
I'm trying to enable the 3.7.x version of this plugin (20171201-3.7.x.ez) on Mac OSX with Erlang/OTP 21 64bit. Here is the url I used to download the plugin:
`curl https://dl.bintray.com/rabbitmq/community-plugins/3.7.x/rabbitmq_delayed_message_exchange/rabbitmq_delayed_message_exchange-20171201-3.7.x.zip -o rabbitmq_delayed_message_exchange-20171201-3.7.x.zip`

Here is the result when I run the command `rabbitmq-plugins enable rabbitmq_delayed_message_exchange`:

`Enabling plugins on node rabbit@localhost:
rabbitmq_delayed_message_exchange
{:plugins_not_found, [:rabbitmq_management_visualiser]}`

I already checked the plugins directory using the command `rabbitmq-plugins list`, which return as following:
`Listing plugins with pattern ".*" ...
WARNING - plugins currently enabled but missing: rabbitmq_management_visualiser

 Configured: E = explicitly enabled; e = implicitly enabled
 | Status: * = running on rabbit@localhost
 |/
[E*] rabbitmq_amqp1_0                  3.7.10
[  ] rabbitmq_auth_backend_cache       3.7.10
[  ] rabbitmq_auth_backend_http        3.7.10
[  ] rabbitmq_auth_backend_ldap        3.7.10
[  ] rabbitmq_auth_mechanism_ssl       3.7.10
[  ] rabbitmq_consistent_hash_exchange 3.7.10
[  ] rabbitmq_delayed_message_exchange 20171201-3.7.x
[  ] rabbitmq_event_exchange           3.7.10
[  ] rabbitmq_federation               3.7.10
[  ] rabbitmq_federation_management    3.7.10
[  ] rabbitmq_jms_topic_exchange       3.7.10
[E*] rabbitmq_management               3.7.10
[e*] rabbitmq_management_agent         3.7.10
[E*] rabbitmq_mqtt                     3.7.10
[  ] rabbitmq_peer_discovery_aws       3.7.10
[  ] rabbitmq_peer_discovery_common    3.7.10
[  ] rabbitmq_peer_discovery_consul    3.7.10
[  ] rabbitmq_peer_discovery_etcd      3.7.10
[  ] rabbitmq_peer_discovery_k8s       3.7.10
[  ] rabbitmq_random_exchange          3.7.10
[  ] rabbitmq_recent_history_exchange  3.7.10
[  ] rabbitmq_sharding                 3.7.10
[  ] rabbitmq_shovel                   3.7.10
[  ] rabbitmq_shovel_management        3.7.10
[E*] rabbitmq_stomp                    3.7.10
[  ] rabbitmq_top                      3.7.10
[  ] rabbitmq_tracing                  3.7.10
[  ] rabbitmq_trust_store              3.7.10
[e*] rabbitmq_web_dispatch             3.7.10
[  ] rabbitmq_web_mqtt                 3.7.10
[  ] rabbitmq_web_mqtt_examples        3.7.10
[  ] rabbitmq_web_stomp                3.7.10
[  ] rabbitmq_web_stomp_examples       3.7.10`
-> Meaning the plugins already there !

I already check the file's permission:

-rw-r--r--  1 phamcuong  admin       59 Jan  8 01:47 README
-rw-r--r--  1 phamcuong  admin   108254 Jan  8 01:47 amqp10_client-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    45061 Jan  8 01:47 amqp10_common-3.7.10.ez
-rw-r--r--  1 phamcuong  admin   411476 Jan  8 01:47 amqp_client-3.7.10.ez
-rw-r--r--  1 phamcuong  admin   276438 Jan  8 01:47 cowboy-2.6.1.ez
-rw-r--r--  1 phamcuong  admin   499856 Jan  8 01:47 cowlib-2.7.0.ez
-rw-r--r--  1 phamcuong  admin    69312 Jan  8 01:47 goldrush-0.1.9.ez
-rw-r--r--  1 phamcuong  admin   100435 Jan  8 01:47 jsx-2.9.0.ez
-rw-r--r--  1 phamcuong  admin   233053 Jan  8 01:47 lager-3.6.5.ez
-rw-r--r--  1 phamcuong  admin   709891 Jan  8 01:47 rabbit_common-3.7.10.ez
-rw-r--r--  1 phamcuong  admin   256346 Jan  8 01:47 rabbitmq_amqp1_0-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    31541 Jan  8 01:47 rabbitmq_auth_backend_cache-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    14435 Jan  8 01:47 rabbitmq_auth_backend_http-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    51081 Jan  8 01:47 rabbitmq_auth_backend_ldap-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    20136 Jan  8 01:47 rabbitmq_auth_mechanism_ssl-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    67960 Jan  8 01:47 rabbitmq_aws-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    23723 Jan  8 01:47 rabbitmq_consistent_hash_exchange-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    43958 Jan 16  2018 rabbitmq_delayed_message_exchange-20171201-3.7.x.ez
-rw-r--r--  1 phamcuong  admin    42483 Jan 21 12:42 rabbitmq_delayed_message_exchange-20171201-3.7.x.zip
-rw-r--r--  1 phamcuong  admin    26819 Jan  8 01:47 rabbitmq_event_exchange-3.7.10.ez
-rw-r--r--  1 phamcuong  admin   238119 Jan  8 01:47 rabbitmq_federation-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    14464 Jan  8 01:47 rabbitmq_federation_management-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    27049 Jan  8 01:47 rabbitmq_jms_topic_exchange-3.7.10.ez
-rw-r--r--  1 phamcuong  admin  1053050 Jan  8 01:47 rabbitmq_management-3.7.10.ez
-rw-r--r--  1 phamcuong  admin   181144 Jan  8 01:47 rabbitmq_management_agent-3.7.10.ez
-rw-r--r--  1 phamcuong  admin   157409 Jan  8 01:47 rabbitmq_mqtt-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    25847 Jan  8 01:47 rabbitmq_peer_discovery_aws-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    54737 Jan  8 01:47 rabbitmq_peer_discovery_common-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    50857 Jan  8 01:47 rabbitmq_peer_discovery_consul-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    33749 Jan  8 01:47 rabbitmq_peer_discovery_etcd-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    15016 Jan  8 01:47 rabbitmq_peer_discovery_k8s-3.7.10.ez
-rw-r--r--  1 phamcuong  admin     7700 Jan  8 01:47 rabbitmq_random_exchange-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    19145 Jan  8 01:47 rabbitmq_recent_history_exchange-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    49803 Jan  8 01:47 rabbitmq_sharding-3.7.10.ez
-rw-r--r--  1 phamcuong  admin   178859 Jan  8 01:47 rabbitmq_shovel-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    23996 Jan  8 01:47 rabbitmq_shovel_management-3.7.10.ez
-rw-r--r--  1 phamcuong  admin   147491 Jan  8 01:47 rabbitmq_stomp-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    72079 Jan  8 01:47 rabbitmq_top-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    65496 Jan  8 01:47 rabbitmq_tracing-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    71635 Jan  8 01:47 rabbitmq_trust_store-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    46563 Jan  8 01:47 rabbitmq_web_dispatch-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    44051 Jan  8 01:47 rabbitmq_web_mqtt-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    66336 Jan  8 01:47 rabbitmq_web_mqtt_examples-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    43959 Jan  8 01:47 rabbitmq_web_stomp-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    52025 Jan  8 01:47 rabbitmq_web_stomp_examples-3.7.10.ez
-rw-r--r--  1 phamcuong  admin    89553 Jan  8 01:47 ranch-1.7.1.ez
-rw-r--r--  1 phamcuong  admin    59096 Jan  8 01:47 recon-2.3.6.ez
-rw-r--r--  1 phamcuong  admin    58345 Jan  8 01:47 syslog-3.4.5.ez

Any advise ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The tool mentions what is very likely the root cause twice:

```
{:plugins_not_found, [:rabbitmq_management_visualiser]}
…
WARNING - plugins currently enabled but missing: rabbitmq_management_visualiser
```

The node likely has had `rabbitmq_management_visualiser` enabled previously. That plugin has been discontinued and [no longer ships with RabbitMQ 3.7.x](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.0). Disable it first (perhaps in the `--offline` mode) or [remove it from the enabled plugin file](http://www.rabbitmq.com/plugins.html#enabled-plugins-file) manually, otherwise all plugin management operations are going to fail with more or less the same error.
