### ISSUE TITLE
CLI Report of Delayed Message Counts

### ISSUE THREAD

**Issue by RyanFrantz** [rabbitmq/rabbitmq-delayed-message-exchange#123]
I would like to be able to report the total count of delayed messages within an exchange from the command line. Additionally, it would be great if we could display the count of delayed messages based on their intended queue.

I had a conversation with @michaelklishin about support in the CLI for finding the total count of delayed messages within an exchange. He helped me with an `eval` statement like the following example:

```bash
rabbitmqctl eval 'rabbit_delayed_message:messages_delayed(rabbit_misc:r(<<"vhost_name">>, exchange, <<"exchange_name">>)).'
```

I tested this running RabbitMQ 3.7.13 in a Docker container that I had just started:

```bash
$ docker-compose exec salsa-rabbit rabbitmqctl version
3.7.13

$ docker-compose exec salsa-rabbit rabbitmqctl eval 'rabbit_delayed_message:messages_delayed(rabbit_misc:r(<<"/">>, exchange, <<"salsa">>)).'
0
```

I expected the total count to be `0` since I had just launched the Rabbit instance and had no messages in it.

However, when I send a delayed message (delayed for a few hours) to Rabbit and run the same `eval` command, it still returns `0`. I've confirmed my exchange exists and is of type `x-delayed-message`:

```bash
$ docker-compose exec salsa-rabbit rabbitmqctl list_exchanges
Listing exchanges for vhost / ...
name    type
amq.direct      direct
amq.match       headers
amq.headers     headers
amq.rabbitmq.trace      topic
amq.topic       topic
amq.fanout      fanout
salsa   x-delayed-message  <<<
        direct
```

 **NOTE**: When I run the command for an exchange that doesn't actually exist, I get `0` as well, rather than an error stating the exchange is invalid:

```bash
$ docker-compose exec salsa-rabbit rabbitmqctl eval 'rabbit_delayed_message:messages_delayed(rabbit_misc:r(<<"/">>, exchange, <<"an_exchange_that_does_not_exist">>)).'
0
```

**Comment by michaelklishin** [comment]
This wasn't a part of #3 because CLI command support in plugins was introduced later in the 3.7.0 development cycle. Makes sense 👍

**Comment by adinapoli** [comment]
Hey folks,

thanks for this amazing plugin, it's really appreciated. @michaelklishin I am using the "latest and greatest" version available, i.e. 3.8.0, and I still experience the behaviour described by @RyanFrantz , i.e. the `eval` command always returns 0 for me. What am I doing wrong?

Furthermore, I don't see any trace of the metric (as described [here](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/issues/3#issuecomment-487618965)). Even though my exchange is clearly the right one, I don't see anything in the dashboard:

<img width="778" alt="Screenshot 2020-10-22 at 09 20 06" src="https://user-images.githubusercontent.com/442035/96838260-f3c5eb80-1447-11eb-9f8b-16ab6845ca8e.png">

And if I click on the `+/-` signs I don't see any "delay-related" column I can enable:

<img width="336" alt="Screenshot 2020-10-22 at 09 20 21" src="https://user-images.githubusercontent.com/442035/96838300-04766180-1448-11eb-8d3e-1e9009c5a095.png">

Am I missing something totally obvious here?

I am on a Mac OS X 10.15.6 , I have installed `rabbitmq` via `brew` and I am currently using version `3.8.3` with Erlang version `22.3`.

**Comment by adinapoli** [comment]
> Furthermore, I don't see any trace of the metric (as described here). Even though my exchange is clearly the right one, I don't see anything in the dashboard:

Partially replying to myself: I have upgraded to the latest RMQ and now I can at least see the counter in the page available by clicking on the desired exchange:

<img width="729" alt="Screenshot 2020-10-22 at 09 58 05" src="https://user-images.githubusercontent.com/442035/96842403-46ee6d00-144d-11eb-806c-93261c11ca54.png">

**Comment by michaelklishin** [comment]
This is the metric we expose. This issue is about adding a CLI tools command which would expose the same metric one way or another.

**Comment by zyh-future** [comment]
So how do we get the number of messages backlog in exchange?

**Comment by marguspeet** [comment]
It seems that in case of the latest plugin version (3.10.2) the count in the UI has disappeared.

![Screen Shot 2022-06-14 at 11 58 04](https://user-images.githubusercontent.com/24493036/173537608-99afd330-9545-4395-b882-ea368cc79baa.png)

**Comment by artkom911** [comment]
@michaelklishin 

Unfortunately, you did not want to listen to the arguments in your responses and closed the conversation. https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/issues/228

The management UI that you mentioned uses the same http api, so it is completely useless in this case.

I never said that I delayed messages for months. As a matter of fact, it is mostly hours, even minutes, sometimes days. I simply have lots of them and planned to have more in feature, but hit this issue.
Also, in my case, messages don't have any information except dataId (uuid v4, if this matters). The actual data are already stored in DB.

I do have other options, not rabbit-based, but this solution was easy to try and worth the shot.

I do realize that your lack of experience building high-load systems affects your decisions and point of view. Still, I'm a bit surprised by such a reaction.

Anyway, thx for your time.

**Comment by michaelklishin** [comment]
@artkom911 you are welcome to use any other option. You insults towards open source maintainers will only get you banned from this org, Mr. Scalable System Know-it-all.

**Comment by michaelklishin** [comment]
For those looking to improve the plugin, and not insult our team, I have [laid out our current v2 design for this plugin](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/issues/229), or rather, the few ideas we have.

**Comment by akpmohan07** [comment]
Hi @adinapoli ,
https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/issues/123#issuecomment-714308745

![Image](https://github.com/user-attachments/assets/014d6d65-4db0-420c-8f04-570f581ca197)

Is this count is total count of mesaages processed by an plugin or a current count of messages in the delayed exchane?

**Comment by adinapoli** [comment]
> Hi [@adinapoli](https://github.com/adinapoli) ,
> 
> Is this count is total count of mesaages processed by an plugin or a current count of messages in the delayed exchane? [#123 (comment)](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/issues/123#issuecomment-714308745)
> 
> ![Image](https://github.com/user-attachments/assets/014d6d65-4db0-420c-8f04-570f581ca197)

It has been 5 years, but I think I was referring to the counter you highlighted in green.

**Comment by akpmohan07** [comment]
Thanks for Replying @adinapoli ,
Yeah that highlighted in green is an `current count of message in exchange` or ` total number message recieved by an exchange over the period of time`?

Is it like increase and decrease based on consumption, or it is just like an counter only increase always?

**Comment by gomoripeti** [comment]
the number that is shown on the exchange page of the management UI as `messages delayed` is the current number of messages waiting in the exchange. ie it can decrease.

**Comment by akpmohan07** [comment]
Thanks for the confirmation @gomoripeti

**Comment by akpmohan07** [comment]
Hi @gomoripeti , @adinapoli 
1. Is there any way to view/retrieve the waiting message in exchange , and it's `x-delay` value?
2. And what will be the plugin behaviour,  if the `x-delay` is an neagtive value like `-17` ? (In our client logs we saw some messages are pushed to exchange with negative value)

**Comment by gomoripeti** [comment]
as you have further questions could you open a new Discussion in https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/discussions, as this Issue is about "CLI Report of Delayed Message Counts". Im happy to answer there.
