### ISSUE TITLE
Configure the dead-letter queue conversion queue, and set the message expiration not 5 minutes, 24 hours. When the time arrives, it will occasionally not forward, and it will remain in the dead-letter queue.

### ISSUE THREAD

**Issue by 501956430** [rabbitmq/rabbitmq-delayed-message-exchange#124]
Configure the dead-letter queue conversion queue, and set the message expiration not 5 minutes, 24 hours. When the time arrives, it will occasionally not forward, still stay in the dead-letter queue, use the rabbitmq-manager web client to operate the message: "get message" The message will be forwarded to the exchange queue. What is the reason, why can't it be automatically forwarded after the message expires? Can anyone help me?

code: 
`

@Bean
    public Queue orderDlxQueue(){
        return QueueBuilder.durable("orderDlxQueue")
                .withArgument("x-dead-letter-exchange", "expiration.direct")
                .withArgument("x-dead-letter-routing-key", "order")
                .build();
    }
`
` 
@Bean
    Binding orderDlxMessage() {
        return BindingBuilder.bind(orderDlxQueue()).to(dlxExchange()).with("order-routingKey");
    }`

rabbitmq-service version: 3.7.13
Erlang 21.3.6

**Comment by michaelklishin** [comment]
See the [Limitations](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#limitations) section. Delayed publishing can happen with a different topology, e.g. the exchange or its bindings may or may not be there. There is no way to support the mandatory flag and returns with this exchange type, so [Firehose](https://www.rabbitmq.com/firehose.html) and traffic captures are currently the only troubleshooting tools available.

RabbitMQ 3.8 introduced a new metric to make dropped unroutable messages easier to spot (see https://github.com/rabbitmq/rabbitmq-server/issues/1904).
