### ISSUE TITLE
delayed message got dropped somehow

### ISSUE THREAD

**Issue by cupidcoffee** [rabbitmq/rabbitmq-delayed-message-exchange#125]
Hi guys,  
We use rabbitmq to keep refreshing some data, we achieve it by first send a refresh msg to RMQ delayed exchange, and everytime the consumer got this message, it will refresh the data and send the same msg to the delayed exchange.
The issue we found out is that randomly after send the msg to the delayed exchange, somehow no consumer ever consumed this message again which terminate our refreshing logic.

I read the docs and know that lack of queue might cause the msg dropped in the delayed exchange, but in my case the queue should always be there because after it stopped refreshing, if I send a new refresh msg it will start to refresh again.

**Comment by lukebakken** [comment]
Thank you for using RabbitMQ.

Please first ask your question or discuss your suspected issue on the mailing list:

https://groups.google.com/forum/#!forum/rabbitmq-users

Team RabbitMQ does not use GitHub issues for discussions, investigations, root cause analysis and so on.

Please take the time to read the CONTRIBUTING.md document for instructions on how to effectively ask a question or report a suspected issue:

https://github.com/rabbitmq/rabbitmq-server/blob/master/CONTRIBUTING.md#github-issues

Following these rules will save time for both you and RabbitMQ's maintainers.

Thank you.

**Comment by hahaxiangnile** [comment]
> 嗨，
> 大家好，我们使用rabbitmq来不断刷新一些数据，我们首先通过向RMQ延迟交换发送刷新消息来实现它，每次消费者收到此消息时，它将刷新数据并将相同的消息发送给延迟交换。
> 我们发现的问题是，在将msg发送到延迟的交换之后，随机地，某种程度上没有消费者再次消费了此消息，从而终止了我们的刷新逻辑。
> 
> 我阅读了文档，知道队列不足可能会导致味精在延迟的交换中掉线，但就我而言，该队列应始终存在，因为在停止刷新后，如果我发送新的刷新味精，它将开始再次刷新。

请问您这边解决了嘛，我这边遇到相同的问题,确定版本没有问题,如果您这边解决了方便提供一下解决方案嘛

**Comment by michaelklishin** [comment]
This plugin has several important limitations, e.g. it does not replicate the set of delayed messages (it is node-local) and does not support mandatory publishing. Like any exchange, if there are no queues or other exchanges bound to it, it won't route any messages and they will be dropped. There is a pair of unroutable message metrics in management UI/HTTP API in 3.8 (behind a feature flag). We cannot suggest anything with the amount of information provided.

**Comment by hahaxiangnile** [comment]
> 此插件有几个重要限制，例如，它不复制延迟消息集（它是本地节点），并且不支持强制发布。像任何交换一样，如果没有队列或其他交换绑定到该交换，则它不会路由任何消息，它们将被丢弃。3.8中的管理UI / HTTP API中有一对无法路由的消息指标（在功能标志后面）。我们无法提供所提供的大量信息

> 此插件有几个重要限制，例如，它不复制延迟消息集（它是本地节点），并且不支持强制发布。像任何交换一样，如果没有队列或其他交换绑定到该交换，则它不会路由任何消息，它们将被丢弃。3.8中的管理UI / HTTP API中有一对无法路由的消息指标（在功能标志后面）。我们无法提供所提供的大量信息。

Thank you for your reply. At present, the back-end is a mirror cluster. According to the plug-in restrictions, messages will not be copied in the nodes. Through the trace log, it is found that if the node receiving the message is inconsistent with the node pushing the message, the message will be lost. What is the solution

**Comment by michaelklishin** [comment]
We cannot suggest anything specific with the amount of information provided. How are you conducting the test? What does "inconsistent" mean exactly? As mentioned above and in the plugin's README, messages published as mandatory are not supported by this plugin.

We need an executable example that reproduces the problem. A single sentence problem statement is not enough. We do not guess in this community: guessing is a very time-consuming way of debugging distributed systems.
