### ISSUE TITLE
Support for RabbitMQ 3.8/4.0

### ISSUE THREAD

**Issue by basicsuperuser** [rabbitmq/rabbitmq-delayed-message-exchange#128]
Hi,

Now that RabbitMQ 3.8 and 4.0 is released, this plugin could add support for these versions. There are currently no such releases available on https://dl.bintray.com/rabbitmq/community-plugins/. I noticed commit https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/commit/8d1e3737fa14cd558b2a9efbe2ebbc2d9aebf4a6 for 3.8.0 by @lukebakken, but I believe a binary should be made as well. It is not listed on https://www.rabbitmq.com/community-plugins.html.

Is this on the roadmap?

**Comment by michaelklishin** [comment]
4.0 is definitely not out. All community plugins will be republished soon enough.

**Comment by michaelklishin** [comment]
According to @lukebakken this plugin is one of the compatible ones, so the only thing that has/had to change is the RabbitMQ version range in plugin metadata. Whether we want a new 3.8-specific build is TBD.

**Comment by lukebakken** [comment]
@basicsuperuser please see this release:

https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/tag/v3.8.0

**Comment by ostap0207** [comment]
I am not quite sure if who is supposed to do it, but do you know when can it be added to https://dl.bintray.com/rabbitmq/community-plugins/3.8.x?

**Comment by michaelklishin** [comment]
It will be added when the Concourse pipeline for community plugins is ready.

**Comment by ostap0207** [comment]
Sorry, not quite sure what that means. Is there an ETA?

**Comment by michaelklishin** [comment]
That means that 3.8-compatible (or 3.8-specific) builds of all community plugins will be published to Bintray effectively all at once by [Concourse](https://concourse-ci.org/). We offer no ETA but it doubt it would take, say, a month.
