### ISSUE TITLE
Failure to enable plugin

### ISSUE THREAD

**Issue by kostasp** [rabbitmq/rabbitmq-delayed-message-exchange#13]
I tried to enable the plugin at 3.5.3 rabbitmq installation. Environment is an ubuntu 14.04 environment.

I got the following error

/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.3/plugins$ sudo rabbitmq-plugins enable rabbitmq_delayed_message_exchange
Plugin configuration unchanged.

Applying plugin configuration to rabbit@kostas-ThinkCentre-A85... failed.
Error: {"no such file or directory","rabbitmq_delayed_message_exchange.app"}

**Comment by videlalvaro** [comment]
How did you install the plugin? Did you get it from here? https://www.rabbitmq.com/community-plugins.html

**Comment by kostasp** [comment]
Yes

What i did today was to remove old installation of 3.5.1 version using sudo apt-get remove.
Installed a fresh rabbitmq 3.5.3 using dpkg -i DEB.deb package command and then i enabled the following plugins.

I copied the downloaded ez file

sudo cp ~/dev2/tools/rabbit_3.5.3/rabbitmq_delayed_message_exchange-0.0.1-rmq3.5.x-9bf265e4.ez /usr/lib/rabbitmq/lib/rabbitmq_server-3.5.3/plugins

I enabled the following plugins

sudo rabbitmq-plugins enable rabbitmq_management
sudo rabbitmq-plugins enable rabbitmq_management_agent
sudo rabbitmq-plugins enable rabbitmq_shovel
sudo rabbitmq-plugins enable rabbitmq_shovel_management

And then tried to enable the downloaded plugin using 
sudo rabbitmq-plugins enable rabbitmq_delayed_message_exchange

I got the error that i posted in the previous comment.

After that i tried to do a restart on the server. And i got the following error. Currently unable to restart the server.

kostas@kostas-ThinkCentre-A85:~/dev2/tools/rabbit_3.5.3$ sudo rabbitmq-server — start

BOOT FAILED
===========

Error description:
   {error,{"no such file or directory",
           "rabbitmq_delayed_message_exchange.app"}}

Log files (may contain more information):
   /var/log/rabbitmq/rabbit@kostas-ThinkCentre-A85.log
   /var/log/rabbitmq/rabbit@kostas-ThinkCentre-A85-sasl.log

Stack trace:
   [{app_utils,load_applications,2,[]},
    {app_utils,load_applications,1,[]},
    {rabbit,start_apps,1,[]},
    {rabbit,broker_start,0,[]},
    {rabbit,start_it,1,[]},
    {init,start_it,1,[]},
    {init,start_em,1,[]}]

{"init terminating in do_boot",{error,{"no such file or directory","rabbitmq_delayed_message_exchange.app"}}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()

**Comment by michaelklishin** [comment]
```
sudo cp ~/dev2/tools/rabbit_3.5.3/rabbitmq_delayed_message_exchange-0.0.1-rmq3.5.x-9bf265e4.ez /usr/lib/rabbitmq/lib/rabbitmq_server-3.5.3/plugins
```

RabbitMQ server does not run as root but `rabbitmq_delayed_message_exchange-0.0.1-rmq3.5.x-9bf265e4.ez` is now owned by root.

**Comment by kostasp** [comment]
Actually All of the plugins (With the way i installed rabbit) are owned by root.
An ll command under my plugins folder shows

-rw-r----- 1 root root  29282 Ιούν 25 13:22 rabbitmq_delayed_message_exchange-0.0.1-rmq3.5.x-9bf265e4.ez
-rw-r--r-- 1 root root 148677 Μάι  22 13:21 rabbitmq_federation-3.5.3.ez

So it was clearly a matter of read access. (Should have figure it out). I gave full access to that file 
sudo chmod 777  rabbitmq_delayed_message_exchange-0.0.1-rmq3.5.x-9bf265e4.ez

And now an ll command shows the following. After that the problem is solved.
-rwxrwxrwx 1 root root  29282 Ιούν 25 13:22 rabbitmq_delayed_message_exchange-0.0.1-rmq3.5.x-9bf265e4.ez*
-rw-r--r-- 1 root root 148677 Μάι  22 13:21 rabbitmq_federation-3.5.3.ez

I then run 
sudo rabbitmq-plugins enable rabbitmq_delayed_message_exchange
Plugin configuration unchanged.

Applying plugin configuration to rabbit@kostas-ThinkCentre-A85... nothing to do.

AND THE PROBLEM IS SOLVED. THANK YOU FOR ACTIVE SUPPORT :)

**Comment by yangchun** [comment]
please change your version
