### ISSUE TITLE
rabbitmq-delayed-message-exchange-3.8.0 not compatible rabbitmq-3.8.1

### ISSUE THREAD

**Issue by lb151** [rabbitmq/rabbitmq-delayed-message-exchange#131]
environment:win10,rabbitmq3.8.1
F:\rabbitmq\rabbitmq_server-3.8.1\sbin>rabbitmq-plugins enable rabbitmq_delayed_message_exchange
Enabling plugins on node rabbit@USERCHI-1H0BT4J:
rabbitmq_delayed_message_exchange
The following plugins have been configured:
  rabbitmq_delayed_message_exchange
  rabbitmq_management
  rabbitmq_management_agent
  rabbitmq_web_dispatch
Applying plugin configuration to rabbit@USERCHI-1H0BT4J...
Plugin configuration unchanged.

but wen i add exchange in web management tip:
Invalid argument, 'x-delayed-type' must be an existing exchange type

**Comment by michaelklishin** [comment]
The type name is not `x-delayed-type`, it is `x-delayed-message`. The plugin is compatible:

<img width="809" alt="Screenshot 2019-11-29 at 17 19 00" src="https://user-images.githubusercontent.com/1090/69874603-7e4faa80-12cc-11ea-8988-303fe50b251c.png">
