### ISSUE TITLE
messagethat have not been routed to the queue will lost when broker restart using rabbitmq-delayed-message-exchange plugin.

### ISSUE THREAD

**Issue by zhuangzhuangdashen** [rabbitmq/rabbitmq-delayed-message-exchange#133]
Thank you for using RabbitMQ.

**STOP NOW AND READ THIS** BEFORE OPENING A NEW ISSUE ON GITHUB

Unless you are CERTAIN you have found a reproducible problem in RabbitMQ or
have a **specific, actionable** suggestion for our team, you must first ask
your question or discuss your suspected issue on the mailing list:

https://groups.google.com/forum/#!forum/rabbitmq-users

Team RabbitMQ does not use GitHub issues for discussions, investigations, root
cause analysis and so on.

Please take the time to read the CONTRIBUTING.md document for instructions on
how to effectively ask a question or report a suspected issue:

https://github.com/rabbitmq/rabbitmq-server/blob/master/CONTRIBUTING.md#github-issues

Following these rules **will save time** for both you and RabbitMQ's maintainers.

Thank you.

**Comment by michaelklishin** [comment]
Because this plugin is not distributed at the moment. [Limitations](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#limitations) in the README says exactly that.

**Comment by zhuangzhuangdashen** [comment]
many thanks for your answer. this helped me.

will there have distributed implementation to prevent the message that haven't been delivered  lost at soon?

**Comment by michaelklishin** [comment]
A Raft-based distributed version (a new plugin) is planned but there is no ETA.

I'd also recommend taking a look at the [Publisher Safety](https://www.rabbitmq.com/publishers.html#data-safety) section in the docs as there are many aspects to data safety.

**Comment by zhuangzhuangdashen** [comment]
Ok, will read it in earnest.

thank you again.
