### ISSUE TITLE
Compatibility with since rabbitmq 3.8.4

### ISSUE THREAD

**Issue by exeos** [rabbitmq/rabbitmq-delayed-message-exchange#140]
Hello,
Since rabbitmq 3.8.4 i have logs duplicate error each n second that appear even if the plugins is working.

Problem reading some plugins: [
{"/usr/lib/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.8.0.ez", duplicate_plugin}
]

Do you have same issue ?
It's perfectly working with rabbitmq 3.8.3

**Comment by michaelklishin** [comment]
You have two versions of this plugin on code path. One of them (the older one) must be removed. It would work exactly the same way with any RabbitMQ version. My guess is that you have downloaded a different version of this plugin while also retaining the `./plugins` directory of the original (`3.8.3`) installation.

In other news, [3.8.5 is out](https://www.rabbitmq.com/changelog.html) and it addresses a number of regressions in `3.8.4` (unrelated to this plugin but worth an upgrade).
