### ISSUE TITLE
When the machine goes down, the binding for the delayed switch cannot be routed

### ISSUE THREAD

**Issue by dong9205** [rabbitmq/rabbitmq-delayed-message-exchange#145]
HI, When all of my nodes went down, I found that the binding of the delayed switch had to be re-bound, and the routing could not be done without re-binding.

**Comment by michaelklishin** [comment]
[Limitations](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#limitations) explain that this plugin does not replicate its data. A future from scratch version might but even then, losing a majority of nodes will be disruptive to availability, leave alone all nodes.

**Comment by michaelklishin** [comment]
Another important factor is whether the queues bound to this exchange are [durable](https://www.rabbitmq.com/queues.html#durability). If they are not, then their bindings cannot be durable either.
