### ISSUE TITLE
can not create exchange with type x-delayed-type

### ISSUE THREAD

**Issue by daxiong** [rabbitmq/rabbitmq-delayed-message-exchange#15]
I have just enabled rabbitmq_delayed_message_exchange,and my rabbitmq web page  had see x-delayed-type option in add new exchange.

but when i try to create a exchange with type x-delayed-type,it saies "Invalid argument, 'x-delayed-type' must bean existing exchange type "...

my rabbitmq version is 3.4.0 and i downloaded the plugin from the https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/

thanks

**Comment by videlalvaro** [comment]
First, download the plugin from here where it is already compiled: https://www.rabbitmq.com/community-plugins.html

`'x-delayed-type'` is an argument you set when declaring the exchange to tell the plugin how do you want the exchange to behave, for example, as a _direct_ exchange, or _fanout_ exchange, etc. So the value of that argument must be the type of an exchange present in your installation.

**Comment by michaelklishin** [comment]
It would help a lot if you provided the code that you used and questions were asked on the mailing list.

**Comment by ericuldall** [comment]
I installed the .ez file from the community link and when trying to add a new exchange in the admin with x-delayed-type I get the same error. Any info on this? Not sure why an unresolved ticket was closed.

**Comment by videlalvaro** [comment]
What value do you set for your `x-delayed-type`? 

Could you provide us more info?

Can you share a minimum code example in order to reproduce your issue?

**Comment by ericuldall** [comment]
There is no code. I'm using the GUI admin dashboard that comes with rabbit MQ.
![screen shot 2015-06-26 at 3 32 37 pm](https://cloud.githubusercontent.com/assets/3223296/8388576/987fbd96-1c18-11e5-8e2b-60c97824c790.png)
![screen shot 2015-04-20 at 11 17 45 am](https://cloud.githubusercontent.com/assets/3223296/8388578/99a555e6-1c18-11e5-8380-f0310ea6b26c.png)

**Comment by ericuldall** [comment]
![screen shot 2015-06-26 at 3 32 30 pm](https://cloud.githubusercontent.com/assets/3223296/8388582/a57e569c-1c18-11e5-91e1-19a58887731a.png)

**Comment by videlalvaro** [comment]
There you don't seem to provide the `x-delayed-type` exchange argument as explained on the README [1], and on my answer above in this issue [2].

1- https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#routing
2- https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/issues/15#issuecomment-115202562

**Comment by ericuldall** [comment]
Hey, that worked. I missed that arguments part. Sorry for my ignorance, I've been using rabbit for a whole 10 minutes now.

**Comment by videlalvaro** [comment]
No worries. For general questions we have the RabbitMQ Google Group: https://groups.google.com/forum/#!forum/rabbitmq-users
