### ISSUE TITLE
delay message timing is not accurate

### ISSUE THREAD

**Issue by echobool** [rabbitmq/rabbitmq-delayed-message-exchange#153]
My delay message timing is not accurate, in the case of 120 minutes, there will be tens of seconds ahead of time for consumption, which is not fixed.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
We cannot suggest much without any logs or node load metrics. This is not something that has been reported elsewhere and the scheduling algorithm is not particularly complicated. It may also matter how the message is routed by the actual underlying exchange and how the results of the publishing are observed. This is mailing list material.
