### ISSUE TITLE
How to get rabbitmq_delayed_message_exchange-20171215-3.6.x.zip ?

### ISSUE THREAD

**Issue by charnet1019** [rabbitmq/rabbitmq-delayed-message-exchange#159]
Rabbitmq Version: 3.6.14

Forbidden to access https://dl.bintray.com/rabbitmq/community-plugins/3.6.x/rabbitmq_delayed_message_exchange/rabbitmq_delayed_message_exchange-20171215-3.6.x.zip, 
are there other download channels?

Thanks

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
