### ISSUE TITLE
How to get rabbitmq_delayed_message_exchange-20171215-3.6.x.zip

### ISSUE THREAD

**Issue by charnet1019** [rabbitmq/rabbitmq-delayed-message-exchange#161]
Rabbitmq version: 3.6.14

Forbidden access to https://dl.bintray.com/rabbitmq/community-plugins/3.6.x/rabbitmq_delayed_message_exchange/rabbitmq_delayed_message_exchange-20171215-3.6.x.zip,
are there other download channels?

Thanks

**Comment by michaelklishin** [comment]
Duplicate of #159.
