### ISSUE TITLE
Binary build 3.8.17.8f537ac.ez shows up with previous version number 3.8.9

### ISSUE THREAD

**Issue by danm-de** [rabbitmq/rabbitmq-delayed-message-exchange#164]
Hi, I've just updated the plugin and was wondering why `rabbitmq-plugins list` still prints out the previous version number '3.8.9'.

$ rabbitmq-plugins list
[E*] rabbitmq_delayed_message_exchange 3.8.9+1.g8f537ac

It seems that it's hard-coded in the new binary (maybe a build script issue?).

**Comment by michaelklishin** [comment]
Because of build target idiosyncracies that only affect such non-core plugins.
