### ISSUE TITLE
Message getting lost without error or warning 

### ISSUE THREAD

**Issue by shkelzeen** [rabbitmq/rabbitmq-delayed-message-exchange#178]
I have a scenario as follow. I have an exchange `E` which is bind with queue `Q`, have a scheduler which puts around 1000 messages on the exchange and all the messages are passed to the queue and I receive them on the listener, while I am processing the messages if a error happens messages are send to a other fanout  delayed exchange `FD` with a delay of 60s and this process is repeated until all the messages are processed. The issue is for some reason some messages which are being put on `FD` are getting lost with error warning

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
