### ISSUE TITLE
Support for Amanon MQ on AWS

### ISSUE THREAD

**Issue by adambezecny** [rabbitmq/rabbitmq-delayed-message-exchange#181]
Hi,

is it possible to run this plughin on Amazon MQ? AWS documentation does not mention this: https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/rabbitmq-basic-elements-plugins.html

I am wondering whether there is any workaround how to enable it

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
