### ISSUE TITLE
 'x-delayed-type' must bean existing exchange type 

### ISSUE THREAD

**Issue by benhsu** [rabbitmq/rabbitmq-delayed-message-exchange#19]
Hello

I installed this plugin and when I try to declare an exchange, I get this error message when I declare an exchange in my GUI

406 PRECONDITION_FAILED - Invalid argument, 'x-delayed-type' must bean existing exchange type 

<code>x-delayed-type</code> is showing up as a dropdown option in the management GUI, and <code>rabbitmq-plugins list</code> shows it as installed

Is there some erlang data structure I can inspect to see what went wrong? I am trying to learn erlang so I'm happy to poke around my environment with some guidance.

(also notice the misspelling, "be an" ==> "bean". I can't find where that error is coming from)

**Comment by benhsu** [comment]
I am running rabbitmq 3.5.3

**Comment by benhsu** [comment]
Looks like I got "x-delayed-message"  (the exchange type to declare) and "x-delayed-type" (the additional header) mixed up

**Comment by videlalvaro** [comment]
Fixed the typo: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/commit/8449cf620d2ba0a8e8a34b9da78651ed298e8671

Yes, once thing is to declare an exchange as `x-delayed-message`, but then you must provide the header telling the exchange which routing behaviour to adopt.

**Comment by dotnetooo** [comment]
we have installed 3.5.4 RabbitMQ version and get the same error.

**Comment by Paxa** [comment]
Got same error because forget to add `x-delayed-type`. Why example only in Java?

This worked for me:
```
rabbitmqadmin declare exchange name=bunny_delay type=x-delayed-message arguments='{"x-delayed-type": "direct"}'
```

**Comment by videlalvaro** [comment]
@Paxa feel free to send a PR to the README adding that example
