### ISSUE TITLE
Please add support for rabbit 3.10

### ISSUE THREAD

**Issue by fernandomacho** [rabbitmq/rabbitmq-delayed-message-exchange#194]
Hi, can you add support for rabbit 3.10 series?

Thanks in advance

**Comment by fernandomacho** [comment]
Thanks, has you compile new version with new metadata requirements?? On repo I show the last available version was upload on 26 of jul.

Best regards

**Comment by michaelklishin** [comment]
A new release [is out](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/tag/3.10.0).
