### ISSUE TITLE
"x-delayed-type = direct" does not work with direct_exchange_routing_v2 enabled

### ISSUE THREAD

**Issue by gomoripeti** [rabbitmq/rabbitmq-delayed-message-exchange#199]
The delayed exchange when `x-delayed-type = direct` will use `rabbit_exchange_type_direct:route/2` to route messages, which in turn, if `direct_exchange_routing_v2` feature is enabled will use the `rabbit_index_route` table. However that table is only populated if exchange type is `direct`, not when it is `x-delayed-message`.

How to solve this?
- a possible workaround could be to write to the `rabbit_index_route` table from `rabbit_exchange_type_delayed_message:add_binding/3` callback
- however I feel instead `rabbit_binding` should provide some API to allow 3rd party exchanges to opt into using the v2 index
- or maybe `rabbit_binding:sync_index_route` should be executed in `rabbit_exchange_type_direct:add_binding` instead? (which is also called by `rabbit_exchange_type_delayed_message:add_binding` in this case)

**Comment by michaelklishin** [comment]
`direct_exchange_routing_v2` is only available in `master`, so future RabbitMQ 3.11. We expect
more changes in this area to land before 3.11.0 ships in the second half of this year.

I think it's fine for plugins like this one to update the index tables in the core, in
particular if we introduce functions for a few most common cases. This exchange is fairly
special and it already has to do more than most exchange types.

@ansd do you have an opinion?

**Comment by gomoripeti** [comment]
ah, sorry, I was running common_test of this repo on my branch and apparently it fetched master of RabbitMQ, and I confused all the optimisations that are included and not yet included in recent versions.

an off-topic makefile question: how do I pin RabbitMQ version when developing this plugin (on a feature branch)? I thought its defined here https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/blob/master/Makefile#L5 but it looks like rabbitmq-components.mk overrides that and falls back to master if there is no matching branch in rabbitmq-server https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/blob/master/rabbitmq-components.mk#L33-L38

**Comment by michaelklishin** [comment]
Clone it under `deps` of the `rabbitmq-server` which is checked out to the branch you want. With Erlang.mk, using one clone per branch is practically inevitable.

**Comment by ansd** [comment]
Thanks for reporting this @gomoripeti. 
I missed running this plugin's test suite against rabbitmq-server master branch.

I think for now, the easiest option is implemented in https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/pull/200. In there, we just continue to use direct exchange routing v1 (even if feature flag `direct_exchange_routing_v2` is enabled).

This way this plugin will not have any (negative or positive) performance impact and just continues to work as before.
We can think about whether we extend the binding API to allow tier 2 plugins to also add their bindings into `rabbit_index_route` table in the future. But for now, let's keep things simple.

**Comment by gomoripeti** [comment]
thanks @ansd , I did not think of this simple fix
the PR branch works for me perfectly
