### ISSUE TITLE
Please add support for 3.11 series

### ISSUE THREAD

**Issue by fernandomacho** [rabbitmq/rabbitmq-delayed-message-exchange#209]
Hi, can you add support for 3.11 series?

Thanks in advance

**Comment by bitclicker** [comment]
I haven't used this plugin for very long but just curious, would this be as easy as updating the makefile to include 3.11.x ? if so i'm more than happy to send a PR

**Comment by lukebakken** [comment]
I will get this next week.

**Comment by michaelklishin** [comment]
[Done](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/tag/3.11.1). Note that just like RabbitMQ 3.11, this release *requires Erlang 25*.

**Comment by fernandomacho** [comment]
Thanks!!!

**Comment by lukebakken** [comment]
Thanks @michaelklishin

**Comment by fernandomacho** [comment]
Hi this version support 3.11 series or only 3.11.1 ? Rabbit publish new version 3.11.2-1 Works?
