### ISSUE TITLE
Cannot declare an exchange of this type with RabbitMQ 3.11.7

### ISSUE THREAD

**Issue by fernandomacho** [rabbitmq/rabbitmq-delayed-message-exchange#213]
Hi after upgrade to last release of rabbitmq 3.11.7 this pluging is wrong
if try to add an exchange of type x-delayed with this params:

![image](https://user-images.githubusercontent.com/62182142/213399318-9e0936e3-2656-4918-b1ce-f67ad9ebecf7.png)

get the error
![image](https://user-images.githubusercontent.com/62182142/213399425-88f0f14e-aa38-4baf-9948-0067997793e6.png)

If try to access over web admin to exchanges I don´t get response

if over rabbitmqctl tool, execute rabbitmqctl list_exchanges

get the list with type x-delayed-message

name	type
amq.fanout	fanout
retry_process_survey	x-delayed-message
retry_pp_send_v1.0	x-delayed-message

**Comment by lukebakken** [comment]
I can reproduce this and am investigating.

**Comment by lukebakken** [comment]
In the `Arguments:` field, you must add `x-delayed-type` to the first input box, then in the second input box, add the existing type of exchange you'd like to be delayed: `direct`, `topic`, `fanout`, etc.

Here is where it is documented:
https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#usage
