### ISSUE TITLE
Support for RabbitMQ 3.11.11

### ISSUE THREAD

**Issue by nat-ray** [rabbitmq/rabbitmq-delayed-message-exchange#224]
### Describe the bug

I have upgraded RabbitMQ in my K8s cluster to 3.11.11. In my Terraform module, I have followed the guidance in the default values given [here in Artifacthub](https://artifacthub.io/packages/helm/bitnami/rabbitmq?modal=values&path=plugins): 

```
  additional_values = <<-EOF
    extraPlugins: "rabbitmq_delayed_message_exchange"
```

This worked for our previous version (3.8.6), but after the upgrade I see it was not installed when running `rabbitmq-plugins list`. Is this supported on RabbitMQ 3.11.11? 

### Reproduction steps

n/a

### Expected behavior

Plugin is available

**Comment by michaelklishin** [comment]
To use this plugin with 3.11 you need a version built against and for 3.11. See the Releases page in this repo.

This is how it works for all release series of this and other plugins.

**Comment by nat-ray** [comment]
@michaelklishin Thank you for clarifying, that resolved it for me.
