### ISSUE TITLE
monitoring delayed messages count

### ISSUE THREAD

**Issue by artkom911** [rabbitmq/rabbitmq-delayed-message-exchange#228]
### Is your feature request related to a problem? Please describe.

Hi. 
Having some experience with this plugin I've found out that monitoring delayed messages count can be very resource-greedy.
(https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/issues/123)

If I have hundreds or thousands of messages - all is fine.

But millions of them will change the game - it starts to be very memory and cpu consuming.

For instance, delaying only 3m messages will "cost" you about 17G ram memory to get this info from Rabbit using HTTP API, and will take from 13 to 17 seconds to perform this operation on my server.

Seems like Rabbit literally calculates the number of messages (as mysql > "select count(1) from", not "show table status like", if you are familiar with it). 

More delayed messages results in much more resources, and this can make your server unstable if you want to monitor it on a regular basis.

Maybe there is or will be a better (cheaper in terms of resources) way to monitor this?

I hope so, otherwise, this solution is totally not for big systems and those who care about monitoring.

### Describe the solution you'd like

I'd like to have a cheap and easy way to get this info out of Rabbit. 

It could be an approximate number, doesn't need to be 100% accurate, since it changes all the time.

For e.g. earlier mentioned example mysql > "show table status like" would be perfect.

**Comment by michaelklishin** [comment]
17 upvotes in less than an hour. Sounds legit.

**Comment by michaelklishin** [comment]
This metric is [already exposed](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/issues/123#issuecomment-714308745) on the exchange page in the management UI.

**Comment by michaelklishin** [comment]
Both [Limitations](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#limitations) and [Intended Use Cases](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#intended-use-cases) in the README clearly state that this plugin is NOT designed to delay messages for months and store millions of them.

This plugin is not a data store. Use a suitable data store and an external scheduler of some kind.

**Comment by michaelklishin** [comment]
FTR, @artkom911 decided to go on and insult our team in comments to other issues, and was subsequently banned from the RabbitMQ org. Great job, Mr. Scalability Know-it-all.

> this solution is totally not for big systems and those who care about monitoring

is exactly what the README and my comment above were trying to say. This plugin has too many
limitations to be useful beyond a certain scale.

I had some interest in prototyping a new version of this plugin after we ship 3.12.0 but
@artkom911's uncivil attitude has made me reconsider.
