### ISSUE TITLE
Support delay greater than 4294967295

### ISSUE THREAD

**Issue by dstarcev** [rabbitmq/rabbitmq-delayed-message-exchange#23]
We are using this plugin to delay events for months or years. Unfortunately, plugin currently supports max delay of 4294967295ms (~50days):

```-define(ERL_MAX_T, 4294967295). %% Max timer delay, per Erlang docs.```

```
{ok, Delay} when Delay > 0, Delay =< ?ERL_MAX_T ->
    rabbit_delayed_message:delay_message(Exchange, Delivery, Delay);
_ ->
    nodelay
```

I understand that erlang:start_timer has limit, but it would be nice to implement some kind of reschedule algorithm for large delays.

**Comment by videlalvaro** [comment]
This should be doable, since message expiration at the broker level works in a similar way

**Comment by videlalvaro** [comment]
We have this logic in place already in case you want to try a PR https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_misc.erl#L1093

**Comment by aditbiswas1** [comment]
hi, could you share the PR for this again? i'm not able to open the link

**Comment by hairyhum** [comment]
@aditbiswas1 file has been moved to `rabbitmq-common` repo https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_misc.erl#L1092

**Comment by aditbiswas1** [comment]
thank you

**Comment by aditbiswas1** [comment]
Hi, is there a recommended limit to how much maximum delay I can put on a message? I was curious because the default limit is around 50 days. I'm planning to use this for queuing reminder messages, not sure if this is the appropriate place to ask this.

**Comment by michaelklishin** [comment]
@aditbiswas1 please ask on `rabbitmq-users`. We don't intend this plugin to be used for long term storage, so if you need more than 50 days, I'd say, this is out of scope for this plugin.

**Comment by michaelklishin** [comment]
I'm not sure this is in scope for this plugin. Closing for now.
