### ISSUE TITLE
Get error message

### ISSUE THREAD

**Issue by dotnetooo** [rabbitmq/rabbitmq-delayed-message-exchange#24]
Here is what get when trying to publish message to x-delayed-message type exchange:
{AMQP close-reason, initiated by Peer, code=541, text="INTERNAL_ERROR", classId=0, methodId=0, cause=}

**Comment by dotnetooo** [comment]
were are on RabbitMQ Version 3.1.5

**Comment by videlalvaro** [comment]
What version of the plugin are you using? Make sure it's compatible

**Comment by videlalvaro** [comment]
I think this plugin only work with 3.5.x versions of the broker and higher.

**Comment by dotnetooo** [comment]
Thank you, Alvaro!
I  will check on it.
Rus

**Comment by dotnetooo** [comment]
I think  you are correct. 
https://github.com/rabbitmq/rabbitmq-delayed-message-exchange.
This plugin targets RabbitMQ 3.5.3 and later versions.

**Comment by dotnetooo** [comment]
Thank you  so much , i am closing the issue.
Rus
