### ISSUE TITLE
Do not discard expired message during RabbitMQ-Server's restarting

### ISSUE THREAD

**Issue by pycuichen** [rabbitmq/rabbitmq-delayed-message-exchange#25]
In my situation, I do not wish to discard any messages during messages' delaying. But I notice when I use x-delayed-message type exchange, the message is Lost if its expired time just between the server's down time.

Is there any way to ensure the message' arrival ?

**Comment by michaelklishin** [comment]
This plugin certainly can and will store messages on disk on disk RabbitMQ nodes (which is 99% of installations). We can't do much about several edge cases around broker restarts, however. Can you describe a specific scenario, step by step?

**Comment by michaelklishin** [comment]
OK, looks like this is closely related to #8, closing.
