### ISSUE TITLE
Extending based on dynamic time window function and message quantity grouping delivery threshold.

### ISSUE THREAD

**Issue by tenglongwentian** [rabbitmq/rabbitmq-delayed-message-exchange#252]
### Is your feature request related to a problem? Please describe.

Extending based on dynamic time window function and message quantity grouping delivery threshold.

1. Deliver to the specified queue when the message reaches the grouping quantity.
    For example, setting the message grouping delivery threshold to 50 means that when this threshold of 50 messages is reached, all 50 messages will be delivered to the specified queue.
2. When the message reaches the grouping time, it will be delivered to the specified queue.
   For example, setting the message grouping time to 5 minutes means that messages delivered within 5 minutes will be delivered to the specified queue at the same time.
3. Delivery will be triggered if either condition, 5 minutes or 50 messages, is met.

### Describe the solution you'd like

Extending based on dynamic time window function and message quantity grouping delivery threshold.

1. Deliver to the specified queue when the message reaches the grouping quantity.
    For example, setting the message grouping delivery threshold to 50 means that when this threshold of 50 messages is reached, all 50 messages will be delivered to the specified queue.
2. When the message reaches the grouping time, it will be delivered to the specified queue.
   For example, setting the message grouping time to 5 minutes means that messages delivered within 5 minutes will be delivered to the specified queue at the same time.
3. Delivery will be triggered if either condition, 5 minutes or 50 messages, is met.

### Describe alternatives you've considered

Extending based on dynamic time window function and message quantity grouping delivery threshold.

1. Deliver to the specified queue when the message reaches the grouping quantity.
    For example, setting the message grouping delivery threshold to 50 means that when this threshold of 50 messages is reached, all 50 messages will be delivered to the specified queue.
2. When the message reaches the grouping time, it will be delivered to the specified queue.
   For example, setting the message grouping time to 5 minutes means that messages delivered within 5 minutes will be delivered to the specified queue at the same time.
3. Delivery will be triggered if either condition, 5 minutes or 50 messages, is met.

### Additional context

Extending based on dynamic time window function and message quantity grouping delivery threshold.

1. Deliver to the specified queue when the message reaches the grouping quantity.
    For example, setting the message grouping delivery threshold to 50 means that when this threshold of 50 messages is reached, all 50 messages will be delivered to the specified queue.
2. When the message reaches the grouping time, it will be delivered to the specified queue.
   For example, setting the message grouping time to 5 minutes means that messages delivered within 5 minutes will be delivered to the specified queue at the same time.
3. Delivery will be triggered if either condition, 5 minutes or 50 messages, is met.

**Comment by michaelklishin** [comment]
Thank you for taking the time to describe what you'd like but this plugin will then do two different things and we would really prefer to never repeat that mistake again.

Besides, all time investment this plugin will receive in the next 6-12 months is a v2 rewrite (#229).

Someone (including yourself) can develop a plugin that would do what you want on top of streams.
