### ISSUE TITLE
406 PRECONDITION_FAILED - Invalid argument, 'x-delayed-type' must bean existing exchange type

### ISSUE THREAD

**Issue by dotnetooo** [rabbitmq/rabbitmq-delayed-message-exchange#26]
We have upgraded to RabbitMQ 3.5.4 , installed x-delayed-message plugin.
I get that error while trying to declare  x-delayed-message type exchange.

**Comment by michaelklishin** [comment]
You need to reinstall 3rd party plugins when upgrading. Please post questions to rabbitmq-users.

**Comment by videlalvaro** [comment]
As the error says, the exchange type specified for the `x-delayed-type` declare argument must be of an existing exchange.

**Comment by dotnetooo** [comment]
We have figured it out.

**Comment by AnotherDeveloper01** [comment]
We upgraded to RabbitMQ 3.5.6. Getting the same error as mentioned in this thread when trying to create a 'x-delayed-message' exchange.  Please help

**Comment by videlalvaro** [comment]
@AnotherDeveloper01 have you followed the README on how to declare this exchange? What code are you using for declaring an exchange?

**Comment by AnotherDeveloper01** [comment]
We are trying to directly declare an exchange in the rabbit mq ui directly.

**Comment by videlalvaro** [comment]
@AnotherDeveloper01 are you providing arguments to the declare as explained in the README? Specifically, have you provided a `x-delayed-type` argument in the Management UI?

**Comment by AnotherDeveloper01** [comment]
@videlalvaro . Thanks. Able to create the exchange

**Comment by videlalvaro** [comment]
@AnotherDeveloper01 do you care to post what was wrong for future reference for other users?

**Comment by AnotherDeveloper01** [comment]
We were not declaring "x-delayed-type" as direct/topic/.. . When we declared the correct type of routing, it created the exchange. Thanks again Alvaro.
