### ISSUE TITLE
Support for RabbitMQ 3.13.x

### ISSUE THREAD

**Issue by mvoelker** [rabbitmq/rabbitmq-delayed-message-exchange#263]
### Is your feature request related to a problem? Please describe.

The rabbitmq-delayed-message-exchange plugin does not list 3.13 as supported version yet.
Version 3.13 of RabbitMQ-Server released recently.
Running e.g. `apt-upgrade` would lead to problems / incompatibility.

### Describe the solution you'd like

Please add version 3.13.x to the list of supported version.

**Comment by xuxusheng** [comment]
+1

**Comment by muhammedfurkan** [comment]
same here

**Comment by michaelklishin** [comment]
Please stop the upvoting fest. If you really need this plugin to be updated for 3.13.0, guess what: this is open source software. You can submit a PR that updates the plugin metadata, build it and test it against 3.13.0, and if all works as expected, announce it to the world.

**Comment by lukebakken** [comment]
Everyone who gave this issue a +1 or comment should take the time to contribute back and test the latest release -

https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/tag/v3.13.0

Thank you.

@maltsev
@clemmayer
@nishchay-manwani-glean
@juvenrui
@Westacular
@PhilippHandle
@gomoripeti
@NoCoker
@johanrhodin
@xuxusheng
@muhammedfurkan

**Comment by maltsev** [comment]
Thanks for releasing a new version!

It works well in my local test environment.

**Comment by PhilippHandle** [comment]
Thanks for updating!
Its works on my local environemnt!

**Comment by lukebakken** [comment]
@maltsev @PhilippHandle - thank you, Team RabbitMQ appreciates the verification.

**Comment by mvoelker** [comment]
Thanks for the effort and releasing a new version.
Update of RabbitMQ server to version 3.13 and installation of the plugin worked without problems.
All unit tests green.
It works on my local environment too.

**Comment by johanrhodin** [comment]
I've verified working with `3.13.0`, but have not yet tested the update procedure (`3.12`->`3.13`)

**Comment by nishchay-manwani-glean** [comment]
Thank you for the release. Update works without any problems and it works on our environment too.

**Comment by lukebakken** [comment]
Thanks everyone, the verification is appreciated.

Please note that this plugin will not work with RabbitMQ 4 / `khepri_db` and there are no plans for Team RabbitMQ to make it compatible.
