### ISSUE TITLE
Support string values in x-delay header for compatibility with STOMP

### ISSUE THREAD

**Issue by cdion** [rabbitmq/rabbitmq-delayed-message-exchange#28]
I would like to use this exchange and the STOMP adapter.  However all headers set via the STOMP protocol have values with type ```string```.

The ```x-delayed-message``` exchange ignores the ```x-delay``` header unless it's type is ```number```.  This makes it impossible to send delayed messages via the STOMP protocol.

I tested this by sending messages directly on the exchange via the rabbitmq web interface.  If you set the header with 'string' selected for the type, the message is delivered immediately.  If you select 'number', it is delayed as expected, and the message header x-delay value is negated as documented.

Would it be possible to modify the exchange so that it attempts to convert x-delay header string values to an integer?

**Comment by michaelklishin** [comment]
@cdion this is a reasonable feature request, thank you.
