### ISSUE TITLE
instantaneous expiration of messages

### ISSUE THREAD

**Issue by chb0github** [rabbitmq/rabbitmq-delayed-message-exchange#29]
We are having difficulty reproducing this, but basically, we have a situation where maybe 1/10 restarts of our service and rabbit, we find that our messages instantaneously deliver message. Logs and testing conclusively prove this. 

As we are having difficultly isolating this problem, Let me ask/assert

If the queue is up without problems
and our service comes up with no complaints
Then there should be (theoretically) no reason to instantly deliver messages put into a delayed exchange?

Under what scenario might this happen? If I can understand this, we can try to come up with a reproduction case.

**to be super clear** when things start and work at all, they work **FOREVER** It's not 1/10 messages that instant delivers, it's 1/10 service restarts make all messages fail.

**Comment by videlalvaro** [comment]
Delays are always set in the future as `Now + SpecifiedDelayInMs` https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/blob/master/src/rabbit_delayed_message.erl#L181

Timers are started as `SomeTimeStampInTheFuture - Now` https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/blob/master/src/rabbit_delayed_message.erl#L164 

The problem with the approaches above is what could happen if the value of `Now` is not correct. 

Maybe your system is experiencing time warps?http://www.erlang.org/doc/apps/erts/time_correction.html#Time_Warp

**Comment by chb0github** [comment]
Ok, I have seen this before. But, we are running this in a docker container. How would you suggest I narrow that down? 

Plus, since delay is relative, it doesn't matter what my client/app says, "now" is relative to each app. Delay 15s from "now" should always work. Let me try to imagine how a timewarp could actually produce an issue.

**Comment by videlalvaro** [comment]
Keep in mind that this is a "now" from the point of view of the RabbitMQ
server, and the OS in which it is running.

I don't know how system time is managed/synchronized on docker.

**Comment by chb0github** [comment]
The more I think On this: While what you say could *totally* explain this behavior, we are seeing it when deployed to local VMs and remote virts in azure. When I have seem this problem in the past it was a HW clock issue -- these can't possible be executing on the same HW. 

I am not ruling out what you say, just trying to figure out how it's possible in our scenario. You definitely gave me a real nugget for thought.

**Comment by videlalvaro** [comment]
The code of the plugin is quite simple, so the only thing I see that could be failing here is if the timeout calculation gets a wrong "now" at some point. [There is now](https://queue.acm.org/detail.cfm?id=2745385), etc.

**Comment by michaelklishin** [comment]
I'm not entirely sure what we can improve to battle potential OS clock changes and drift. Closing.
