### ISSUE TITLE
Support for RabbitMQ 4.0

### ISSUE THREAD

**Issue by caueasantos** [rabbitmq/rabbitmq-delayed-message-exchange#290]
### Is your feature request related to a problem? Please describe.

The `rabbitmq-delayed-message-exchange` plugin does not list 4.0 as supported version yet.

### Describe the solution you'd like

Please add version 4.0 to the list of supported version.

**Comment by michaelklishin** [comment]
It's a matter of tweaking one version boundary, building and testing the plugin. Well, in the context of 4.0 I guess doing the same with Khepri enabled would be very useful just to confirm.

**Comment by michaelklishin** [comment]
Team RabbitMQ would like to see this plugin switched to a 4.0 schema object access API before we claim that we "support 4.0", see https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/pull/291.

It should not take a lot of effort.

**Comment by Snazzie** [comment]
Is there a reason why Delay isnt shipped with main rabbitmq? Message Delay common feature that a lot of services use, and having to somehow DIY plugin download into deployment is weird imo. Is there any plans on making activating this plugin easier?

**Comment by gomoripeti** [comment]
As there are plans to create a commercial version of the delay functionality which would be part of Tanzu RabbitMQ, I doubt the open source version of this plugin will be part of the open-source RabbitMQ release.
Don't want to side track this ticket which is about 4.0 support, but if you have any suggestion how to make it easier to activate the plugin without including it in RabbitMQ, you can open a separate GH Discussion. (I don't feel downloading a `.ez` file to the plugins dir is very complicated)

**Comment by michaelklishin** [comment]
@Snazzie please refrain from hijacking specific, actionable issue with random questions. This repository has Discussions enabled.

**Comment by michaelklishin** [comment]
A follow-up to #291 (the details can be found there): https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/pull/292.

**Comment by michaelklishin** [comment]
As of #292, this plugin is 4.0 compatible with the following limitations:

1. If the cluster uses Mnesia for schema store, nothing changes
2. If the cluster uses Khepri and the plugin is enabled after Khepri, it will start Mnesia, set up a node-local Mnesia replica and schema, and continue working as before
3. **Important**: if the cluster uses Mnesia, then the plugin is enabled, and then Khepri is enabled, the plugin must be disabled and re-enabled, or the node must be restarted. Then it will start Mnesia and… see scenario 2 above

**Comment by michaelklishin** [comment]
@caueasantos @gomoripeti I have built and published [`4.0.2`](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/tag/v4.0.2) to match the current RabbitMQ patch release.

It is intentionally marked as a pre-release. Can you folks test it on your end (so will I). If the current behavior matches the docs, I will mark it as the latest GA release.

**Comment by michaelklishin** [comment]
My tests against a `4.0.2` generic binary build are positive. The plugin works fine with Mnesia and (with a document plugin re-enablement or node restart) Khepri.

Kudos to @gomoripeti for contributing #291 #292 with a bit of guidance from the RabbitMQ core team.

**Comment by gomoripeti** [comment]
thanks for the guidance :) I will test the 4.0.2 release today

**Comment by gomoripeti** [comment]
I couldn't find any issues with 4.0.2 version of the plugin

**Comment by mvoelker** [comment]
Found the time to upgrade to RabbitMQ 4.0.x and install and test the plugin (v4.0.2) now.
Can confirm: All good on my end too. All running as expected. All our unit tests checking queuing and especially delayed queuing and delivery are green.
