### ISSUE TITLE
View number of delayed messages

### ISSUE THREAD

**Issue by simonmacmullen** [rabbitmq/rabbitmq-delayed-message-exchange#3]
At the moment, delayed messages are completely invisible; you can't know any even exist. It would be useful for sysadmins to be able to see some additional stats on delayed messages.

Ideally this would work the same way as federation and shovel: the plugin itself could support a bare-bones status function that could be invoked as `rabbitmqctl eval  'rabbit_delayed_message_exchange:status().'` or similar, and (later) a management extension could be added that gives you a HTTP API and GUI representation of the same thing.

So at least you should be able to see the number of delayed messages per exchange. It might also be nice to get a clue on when the next one is going to be delivered, and maybe get a persistent / transient breakdown, total size of message bodies in bytes, and other things similar to what queues can report.

**Comment by garex** [comment]
+1

**Comment by michalzalewski** [comment]
+1

**Comment by MalyshevDmitry** [comment]
+1

**Comment by anhuiliujun** [comment]
+1

**Comment by socrates** [comment]
+1

**Comment by pycuichen** [comment]
+1

**Comment by Pretenderr** [comment]
+1

**Comment by mmartinalo** [comment]
+1

**Comment by oloake** [comment]
+1

**Comment by alexegidio** [comment]
+1

**Comment by videlalvaro** [comment]
I see there's a lot of interest in this feature, which is cool.

Now, implementing this would be running 1 query against a Mnesia table + displaying said info on a webpage.

Does anybody wants to give it a go? This repo can be a good starting point: https://github.com/rabbitmq/rabbitmq-federation-management

**Comment by cbergau** [comment]
+1 :)

**Comment by muravitskiy** [comment]
+1

**Comment by vinhhrv** [comment]
+1

**Comment by hairyhum** [comment]
This feature requires ability to define type-specific exchange information, so it will go to 3.7.x

**Comment by Paxa** [comment]
+1

**Comment by michaelklishin** [comment]
Will be in `3.7.0`.

**Comment by serhatates** [comment]
+1

**Comment by capripot** [comment]
+1

**Comment by andreydiveev** [comment]
+1

**Comment by doug-k-webster** [comment]
+1

**Comment by michaelklishin** [comment]
This has been resolved and shipping 3.7.0. Locking to cut down on the number of emails our team gets.

**Comment by michaelklishin** [comment]
For those looking for this metric: it is available in the management UI, in the exchanges table, as a separate column. It likely will be hidden by default, use the `+/-` button to display it.

CLI users will have to wait for a dedicated command added to this plugin (I asked someone to file an issue for that). In the meantime,

```
rabbitmqctl eval 'rabbit_delayed_message:messages_delayed(rabbit_misc:r(<<"{vhost_name}">>, exchange, <<"{exchange_name}">>)).'
```

can be used (replace `{vhost_name}` and `{exchange_name}` with actual virtual host and exchange names, the trailing dot is significant.

**Comment by videlalvaro** [comment]
Nice! Congrats on this feature
