### ISSUE TITLE
Message not delayed

### ISSUE THREAD

**Issue by shijufrancis** [rabbitmq/rabbitmq-delayed-message-exchange#32]
I created a new exchange for delayed message delivery (x-delayed-message) and the arguments has been set up using arguments: x-delayed-type:topic

I am able to publish the message the delayed exchange but the messages are immediately delivered to to the underlying queue without any delay. I tried to test this using management console by adding the x-delay header.

Can anyone point to any possibilities where I can debug this kind of a behavior? Running RabbitMQ 3.5.6, Erlang 18.1 on Windows OS

**Comment by videlalvaro** [comment]
Can you share the code used to publish delayed messages, and the code used to setup the exchange/bindings/queues?

**Comment by shijufrancis** [comment]
I tried it using management console and from the code. 

 Publisher
-----------

 public class Publisher
    {
        private string _hostName = "localhost";
        private string _userName = "guest";
        private string _password = "guest";
        private string _exchangeName = "DelayedExchange";
        private string _DelayedMessageQueueName = "DelayedQueue";
        private bool _durable = true;

        public IConnection GetRabbitMqConnection()
        {
            ConnectionFactory connectionFactory = new ConnectionFactory();
            connectionFactory.HostName = _hostName;
            connectionFactory.UserName = _userName;
            connectionFactory.Password = _password;

            return connectionFactory.CreateConnection();
        }

        public void SetupDelayedQueue(IModel model)
        {
            Dictionary<string, object> props = new Dictionary<string, object>();
            props.Add("x-delayed-type", ExchangeType.Topic);
            model.ExchangeDeclare("DelayedExchange", "x-delayed-message", true, false, props);

            model.QueueDeclare("DelayedQueue", true, false, false, null);
            model.QueueBind("DelayedQueue", "DelayedExchange", "#");
        }

        public void SendDelayedMessageToDelayedQueue(IModel model)
        {
            IBasicProperties basicProperties = model.CreateBasicProperties();
            basicProperties.SetPersistent(true);
            basicProperties.Headers = new Dictionary<string, object>();
            basicProperties.Headers.Add("x-delay", "60000");

            byte[] payload = Encoding.UTF8.GetBytes("This is a persistent message from Visual Studio");
            PublicationAddress address = new PublicationAddress(ExchangeType.Topic, "DelayedExchange", "#");

            model.BasicPublish(address, basicProperties, payload);
        }
    }


Receiver
------------
    public class Receiver
    {
        private string _hostName = "localhost";
        private string _userName = "guest";
        private string _password = "guest";
        private string _exchangeName = "DelayedExchange";
        private string _DelayedMessageQueueName = "DelayedQueue";
        private bool _durable = true;

        public IConnection GetRabbitMqConnection()
        {
            ConnectionFactory connectionFactory = new ConnectionFactory();
            connectionFactory.HostName = _hostName;
            connectionFactory.UserName = _userName;
            connectionFactory.Password = _password;

            return connectionFactory.CreateConnection();
        }

        public void ReceiveOneWayMessages(IModel model)
        {
            model.BasicQos(0, 1, false); //basic quality of service
            QueueingBasicConsumer consumer = new QueueingBasicConsumer(model);
            model.BasicConsume(_DelayedMessageQueueName, false, consumer);
            while (true)
            {
                BasicDeliverEventArgs deliveryArguments = consumer.Queue.Dequeue() as BasicDeliverEventArgs;
                String message = Encoding.UTF8.GetString(deliveryArguments.Body);
                string delay = Encoding.UTF8.GetString(deliveryArguments.BasicProperties.Headers["x-delay"] as byte[]);
                Console.WriteLine("Message received: {0}", message);
                Console.WriteLine(delay);
                model.BasicAck(deliveryArguments.DeliveryTag, false);
            }
        }

**Comment by videlalvaro** [comment]
Based on your code it does seems that everything should be fine. The only reason I would see why messages are not delayed is if some kind of timing problems are happening between Windows and Erlang. 

Do you have access to some Linux Box/VM to test this on a different env than windows?

**Comment by evgeny-belyaev** [comment]
Same thing for me. Messages are delivered without delay. Windows 7, RabbitMQ 3.5.3, Erlang 18.0
On Ubuntu14.04, RabbitMQ 3.5.7, Erlang R16B03 plugin works just fine.

**Comment by michaelklishin** [comment]
I'm afraid this is a runtime time calculation issue of some kind that we have no control over.

**Comment by mynkow** [comment]
I have exactly the same problem with rabbitmq 3.5.3 on linux. Still investigating...

**Comment by mynkow** [comment]
OK. With rabbitMQ 3.6.1 messages are not delivered at all :(

**Comment by mynkow** [comment]
![image](https://cloud.githubusercontent.com/assets/183151/13754415/9203bd98-ea1f-11e5-8c42-8484683ac643.png)

**Comment by mynkow** [comment]
![untitled](https://cloud.githubusercontent.com/assets/183151/13754450/c4d2f22a-ea1f-11e5-8a27-6e57a89d5722.png)

**Comment by mynkow** [comment]
OK. so if I remove the quotes from `x-delay` everything is working properly.

**Comment by mynkow** [comment]
This is what I get on 3.5.3
```
Got response code 500 with body {"error":"Internal Server Error","reason":"{error,\n {error,function_clause,\n [{rabbit_mgmt_wm_exchange_publish,bad,\n [{{{undef,\n [{time_compat,erlang_system_time,[milli_seconds],[]},\n {rabbit_delayed_message,internal_delay_message,4,\n [{file,\"src/rabbit_delayed_message.erl\"},{line,179}]},\n {rabbit_delayed_message,handle_call,3,\n [{file,\"src/rabbit_delayed_message.erl\"},{line,118}]},\n {gen_server,try_handle_call,4,[{file,\"gen_server.erl\"},{line,607}]},\n {gen_server,handle_msg,5,[{file,\"gen_server.erl\"},{line,639}]},\n {proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]},\n {gen_server,call,\n [rabbit_delayed_message,\n {delay_message,\n {exchange,\n {resource,<<\"/\">>,exchange,\n <<\"OneBigSplash.Vapt.Commands.Scheduler\">>},\n 'x-delayed-message',true,false,false,\n [{<<\"x-delayed-type\">>,longstr,<<\"headers\">>}],\n undefined,undefined,\n {[],[]}},\n {delivery,true,true,<0.4193.0>,\n {basic_message,\n {resource,<<\"/\">>,exchange,\n <<\"OneBigSplash.Vapt.Commands.Scheduler\">>},\n [<<>>],\n {content,60,\n {'P_basic',undefined,undefined,\n [{<<\"752a1575-141c-40c3-846e-d675574f7206\">>,longstr,<<>>},\n {<<\"x-delay\">>,long,10000}],\n 2,undefined,undefined,undefined,undefined,undefined,undefined,\n undefined,undefined,undefined,undefined},\n none,none,\n [<<\"AAAAAAAAAAAA\">>]},\n <<71,54,154,27,82,230,89,38,18,92,13,187,96,147,211,180>>,\n true},\n 1,noflow},\n 10000},\n infinity]}},\n [{gen_server,call,3,[{file,\"gen_server.erl\"},{line,190}]},\n {rabbit_exchange_type_delayed_message,route,2,\n [{file,\"src/rabbit_exchange_type_delayed_message.erl\"},{line,52}]},\n {rabbit_exchange,route1,3,[]},\n {rabbit_exchange,route,2,[]},\n {rabbit_channel,handle_method,3,[]},\n {rabbit_channel,handle_cast,2,[]},\n {gen_server2,handle_msg,2,[]},\n {proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]},\n {wm_reqdata,'POST',http,\n {1,1},\n \"192.168.50.100\",\n {wm_reqstate,#Port<0.8580>,\n [{'content-encoding',\"identity\"},\n {'content-type',\"application/json\"},\n {resource_module,rabbit_mgmt_wm_exchange_publish}],\n undefined,\"192.168.50.100\",\n {wm_reqdata,'POST',http,\n {1,1},\n \"192.168.50.100\",undefined,[],\n \"/api/exchanges/%2F/OneBigSplash.Vapt.Commands.Scheduler/publish\",\n \"/api/exchanges/%2F/OneBigSplash.Vapt.Commands.Scheduler/publish\",\n [{exchange,\"OneBigSplash.Vapt.Commands.Scheduler\"},{vhost,\"%2F\"}],\n [],\"../../../../..\",500,1073741824,67108864,[],[],\n {11,\n {\"host\",\n {'Host',\"docker-local.com:15672\"},\n {\"connection\",\n {'Connection',\"keep-alive\"},\n {\"authorization\",\n {'Authorization',\"Basic Z3Vlc3Q6Z3Vlc3Q=\"},\n {\"accept\",\n {'Accept',\"*/*\"},\n nil,\n {\"accept-encoding\",\n {'Accept-Encoding',\"gzip, deflate\"},\n nil,\n {\"accept-language\",\n {'Accept-Language',\"en-US,en;q=0.8\"},\n nil,nil}}},\n nil},\n {\"content-length\",\n {'Content-Length',\"333\"},\n nil,\n {\"content-type\",\n {'Content-Type',\"text/plain;charset=UTF-8\"},\n nil,nil}}},\n {\"user-agent\",\n {'User-Agent',\n \"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36\"},\n {\"origin\",\n {\"Origin\",\"http://docker-local.com:15672\"},\n nil,\n {\"referer\",{'Referer',\"http://docker-local.com:15672/\"},nil,nil}},\n nil}}},\n not_fetched_yet,false,\n {1,{\"content-type\",{\"Content-Type\",\"application/json\"},nil,nil}},\n <<>>,follow_request,[],80,[]},\n undefined,undefined,\n {wm_log_data,undefined,\n {1457,980317,343163},\n 'POST',\n {11,\n {\"host\",\n {'Host',\"docker-local.com:15672\"},\n {\"connection\",\n {'Connection',\"keep-alive\"},\n {\"authorization\",\n {'Authorization',\"Basic Z3Vlc3Q6Z3Vlc3Q=\"},\n {\"accept\",\n {'Accept',\"*/*\"},\n nil,\n {\"accept-encoding\",\n {'Accept-Encoding',\"gzip, deflate\"},\n nil,\n {\"accept-language\",\n {'Accept-Language',\"en-US,en;q=0.8\"},\n nil,nil}}},\n nil},\n {\"content-length\",\n {'Content-Length',\"333\"},\n nil,\n {\"content-type\",\n {'Content-Type',\"text/plain;charset=UTF-8\"},\n nil,nil}}},\n {\"user-agent\",\n {'User-Agent',\n \"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36\"},\n {\"origin\",\n {\"Origin\",\"http://docker-local.com:15672\"},\n nil,\n {\"referer\",{'Referer',\"http://docker-local.com:15672/\"},nil,nil}},\n nil}}},\n \"192.168.50.100\",\n \"/api/exchanges/%2F/OneBigSplash.Vapt.Commands.Scheduler/publish\",\n {1,1},\n 404,0,undefined,undefined,undefined}},\n [],\"/api/exchanges/%2F/OneBigSplash.Vapt.Commands.Scheduler/publish\",\n \"/api/exchanges/%2F/OneBigSplash.Vapt.Commands.Scheduler/publish\",\n [{exchange,\"OneBigSplash.Vapt.Commands.Scheduler\"},{vhost,\"%2F\"}],\n [],\"../../../../..\",500,1073741824,67108864,[],[],\n {11,\n {\"host\",\n {'Host',\"docker-local.com:15672\"},\n {\"connection\",\n {'Connection',\"keep-alive\"},\n {\"authorization\",\n {'Authorization',\"Basic Z3Vlc3Q6Z3Vlc3Q=\"},\n {\"accept\",\n {'Accept',\"*/*\"},\n nil,\n {\"accept-encoding\",\n {'Accept-Encoding',\"gzip, deflate\"},\n nil,\n {\"accept-language\",{'Accept-Language',\"en-US,en;q=0.8\"},nil,nil}}},\n nil},\n {\"content-length\",\n {'Content-Length',\"333\"},\n nil,\n {\"content-type\",\n {'Content-Type',\"text/plain;charset=UTF-8\"},\n nil,nil}}},\n {\"user-agent\",\n {'User-Agent',\n \"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36\"},\n {\"origin\",\n {\"Origin\",\"http://docker-local.com:15672\"},\n nil,\n {\"referer\",{'Referer',\"http://docker-local.com:15672/\"},nil,nil}},\n nil}}},\n not_fetched_yet,false,\n {1,{\"content-type\",{\"Content-Type\",\"application/json\"},nil,nil}},\n <<>>,follow_request,[],80,[]},\n {context,\n {user,<<\"guest\">>,[administrator],[{rabbit_auth_backend_internal,none}]},\n <<\"guest\">>}],\n []},\n {rabbit_mgmt_util,with_channel,5,[]},\n {rabbit_mgmt_util,with_decode,5,[]},\n {rabbit_mgmt_wm_exchange_publish,process_post,2,[]},\n {webmachine_resource,resource_call,3,[]},\n {webmachine_resource,do,3,[]},\n {webmachine_decision_core,resource_call,1,[]},\n {webmachine_decision_core,decision,1,[]}]}}\n"}
```

**Comment by michaelklishin** [comment]
That issue has nothing to do with the plugin. Please ask questions on RabbitMQ mailing list.

**Comment by Michael754267513** [comment]
@shijufrancis  Message not delayed, settled ?

**Comment by michaelklishin** [comment]
Questions belong to rabbitmq-users. Please include your code and server logs when you post them, as it is absolutely impossible to suggest anything from a single sentence.
