### ISSUE TITLE
Add feature for remove duplicated message

### ISSUE THREAD

**Issue by jiming** [rabbitmq/rabbitmq-delayed-message-exchange#34]
In some case, delayed messaged means no need for duplicated message. What about ignore the message if the delayed queue already contains the same message by certain condition.

**Comment by videlalvaro** [comment]
RabbitMQ queues can't be browsed to see if a particular message is there. So to implement deduplication the plugin would need to keep track of possibly an infinite amount of messages

**Comment by michaelklishin** [comment]
I'm also not sure how we'd let the user express said conditions. This sounds like a significant stretch to what this plugin was originally designed to do.

**Comment by jiming** [comment]
Actually I think no duplicate message is a very important feature in delayed queue.

One reason we need delayed queue is that we want to batch process same messages or trigger one action with multiple same messages. So that we can improve performance of system. 

For example, I receive 100 messages per minute and I can delay them 1 minute and do one action to process all of them if delayed queue remote duplicated message. Otherwise I need do 100 actions to process them.

Talking about how to tell two messages are same, I think by define a property "x-unique-message-code" to compare them is an easy and simple way.

**Comment by utopiafx** [comment]
I agree with Jiming. For my needs, it would be very useful if it duplicate message could be  filter out and only one of them would be sent. 
Especially if i Have lets say connect an multi-chat-room application with notifications.
I don't need everytime someone is written in one of the room, but only once in every lets say 10 seconds. So I know if there are some activity, but not every time. 
I'm convince this could be done somehow. Anyone ?

**Comment by michaelklishin** [comment]
There are no plans to implement deduplication in this plugin at this time, primarily because there are higher priorities for the team. In addition, the current architecture of this plugin will have to change drastically to decently to support deduplication in clusters (see Limitations in the README)

There are projects such as [QDB](https://github.com/qdb-io/qdb-server) and posts that demonstrate how to do deduplication in the consumers, which to me personally sounds like the right way to go about it: this way deduplication logic resides in your application and can be tweaked and redeployed much easier.

**Comment by noxdafox** [comment]
Hello, just FYI I developed a small plugin implementing messages de-duplication at the exchange. If your use case is simple enough, you could chain the two exchanges achieving delayed and deduplicated delivery.

You can find the plugin [here](https://github.com/noxdafox/rabbitmq-message-deduplication). The release includes binaries for RabbitMQ 3.7.

**Comment by utopiafx** [comment]
Thanks noxdafox!. It seems that I already have been migrated over to use a much more simpler solution for realtime app than rabbitmq, by using redis. This solves my kind of problem more suitable and efficient. No extra messages or notifications is performed than the needed ones and its even "secured" to "resend" those message if needed or when the app is reconnected again.

**Comment by fuzzy76** [comment]
How about some tag field that you can filter on. Similar to how routing_info is added to messages?

**Comment by nachitox** [comment]
> Hello, just FYI I developed a small plugin implementing messages de-duplication at the exchange. If your use case is simple enough, you could chain the two exchanges achieving delayed and deduplicated delivery.
> 
> You can find the plugin [here](https://github.com/noxdafox/rabbitmq-message-deduplication). The release includes binaries for RabbitMQ 3.7.

@noxdafox Sorry my ignorance, but how can I do that?

**Comment by noxdafox** [comment]
You can check the exchange-to-exchange section of the manual.

The deduplication exchange acts as a fanout one. Therefore, you could
publish your messages into a deduplication exchange and bind it to the
exchanges you need for more complex routing.

https://www.rabbitmq.com/e2e.html

Il giorno mar 8 giu 2021 alle ore 18:55 Ignacio colautti <
***@***.***> ha scritto:

**Comment by nachitox** [comment]
Thank you.
Yes, I started investigating on that and I'm trying to making it work :)

```
	$this->channel->queue_declare('queue_name', false, true, false, false, false, ['x-message-deduplication' => ['t', true]]);
	$this->channel->exchange_declare('exchange_dedup_name', 'x-message-deduplication', false, true, true, false, false, [
		'x-cache-size'	=> ['I', 500], // maximum number of entries for the deduplication cache. If the deduplication cache fills up, older entries will be removed to give space to new ones.
		'x-cache-ttl'	=> ['I', $this->delay * 1000] // amount of time in milliseconds duplicate headers are kept in cache.  
	]);
	$this->channel->exchange_declare('exchange_delay_name', 'x-delayed-message', false, true, true, false, false, [
		'x-delayed-type' => ['S', 'direct'] // same routing behavior shown by the direct exchange.
	]);
	$this->channel->exchange_bind('exchange_delay_name', 'exchange_dedup_name');
	$this->channel->queue_bind('queue_name', 'exchange_delay_name');
```
