### ISSUE TITLE
Install on fedora 23 breaks with ERROR

### ISSUE THREAD

**Issue by olekhy** [rabbitmq/rabbitmq-delayed-message-exchange#35]
Hey!

after fresh install rabbitmq server on my machine as from http://www.rabbitmq.com/install-rpm.html described i'll enable plugin (download this in /usr/lib/rabbitmq/lib/rabbitmq_server-xxx-version/plugins

run:

`sudo rabbitmq-plugins enable rabbitmq_delayed_message_exchange`

output:

```

The following plugins have been enabled:
  rabbitmq_delayed_message_exchange

Applying plugin configuration to rabbit@x... failed.
Error: {"no such file or directory","rabbitmq_delayed_message_exchange.app"}

```

check that plugin installed:

```
rabbitmq-plugins list | grep delayed
[E ] rabbitmq_delayed_message_exchange 0.0.1

```
installed are:

RabbitMQ 3.6.0, 
Erlang 17.4

**Comment by prolic** [comment]
seems not to work with RabbitMQ 3.6.0, downgrade to 3.5.7 until this plugin is updated.

**Comment by akshay-hazari** [comment]
What version of erlang does it work with?

**Comment by michaelklishin** [comment]
@akshay-hazari plugins do not have Erlang version requirements, RabbitMQ [itself does](http://www.rabbitmq.com/which-erlang.html). The README explains what versions of RabbitMQ this plugin supports.

**Comment by michaelklishin** [comment]
@olekhy that's not a lot of information to suggest much, please describe the exact steps you've taken on rabbitmq-users (which is where such questions belong). The fact that this plugin cannot be located on code path can be due to different reasons but it is no way an indication of incompatibility with a particular RabbitMQ version.

**Comment by akshay-hazari** [comment]
@michaelklishin Thanks . I had been getting an error after installing the plugin , which said incompatible version of erlang with plugin. Had installed erlang R16B03 which made it work.

**Comment by olekhy** [comment]
@michaelklishin sry no more because ive jump to ubuntu again with no issue.
