### ISSUE TITLE
Messages are not sent to queue for delayed exchange or taking more time than configured delay

### ISSUE THREAD

**Issue by seetharamireddy540** [rabbitmq/rabbitmq-delayed-message-exchange#37]
I am Rabbit MQ 3.5.4 I have two types for exchanges one is topic and delayed topic. I am experiencing the following issues with delayed topic once in a while (every 20 - 30days)

Configuration : 
3 node cluster 
12- 15 messages/ sec
delay : 30 sec for each message

Sometime , messages are stuck in one node and not sharing with queues , once we re-start the Rabbit MQ nodes then it all messages release from memory and pushed to queue.

We don't see any issues with non-delayed topic.
Can you pls help me to find is there any issues the delayed topic ?

I see the planning status is still experimental only , so it is not recommended to use in production yet ?

Thanks in advance for your help.

Regards
Ram

**Comment by michaelklishin** [comment]
Runtime timers are not perfect and depend on OS timers. [Time drift and correction](http://erlang.org/doc/apps/erts/time_correction.html) happen over time. Sorry but there's nothing this plugin or RabbitMQ can do about this.

**Comment by michaelklishin** [comment]
"Experimental" means it is relatively new and there's limited understanding on what this plugin should and should not offer. It's definitely like that all new plugins have usability issues and/or bugs.

**Comment by michaelklishin** [comment]
Please start a discussion on rabbitmq-users and provide a piece of code that demonstrates what you do as well as RabbitMQ log files. If a node restart helps then I suspect this plugin encounters an exception. Otherwise see the above notes on imperfect timers.
