### ISSUE TITLE
Channel shutdown: connection error

### ISSUE THREAD

**Issue by lameroot** [rabbitmq/rabbitmq-delayed-message-exchange#38]
Hello!

We use your plugin for redelivery messages. We have next exception (application log):
` o.s.a.r.c.CachingConnectionFactory:281 - Channel shutdown: connection error; protocol method: #method<connection.close>(reply-code=541, reply-text=INTERNAL_ERROR, class-id=0, method-id=0)
`
and next exception (/var/log/rabbitmq/rabbit.log)

** Reason for termination ==
** {{noproc,
        {gen_server,call,
            [rabbit_delayed_message,
             {delay_message,
                 {exchange,
                     {resource,<<"/">>,exchange,<<"test.app.delay">>},
                     'x-delayed-message',true,false,false,
                     [{<<"x-delayed-type">>,longstr,<<"topic">>}],
                     undefined,undefined,
                     {[],[]}},
                 {...skip data},
                 1000},
             infinity]}},
    [{gen_server,call,3,[{file,"gen_server.erl"},{line,190}]},
     {rabbit_exchange_type_delayed_message,route,2,
         [{file,"src/rabbit_exchange_type_delayed_message.erl"},{line,52}]},
     {rabbit_exchange,route1,3,[]},
     {rabbit_exchange,route,2,[]},
     {rabbit_channel,handle_method,3,[]},
     {rabbit_channel,handle_cast,2,[]},
     {gen_server2,handle_msg,2,[]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

	 
=ERROR REPORT==== 31-Jan-2016::09:59:00 ===
Error on AMQP connection <0.24016.59> (127.0.0.1:56710 -> 127.0.0.1:5672, vhost: '/', user: 'guest', state: running), channel 7:
{{noproc,
     {gen_server,call,
         [rabbit_delayed_message,
          {delay_message,
              {exchange,
...skip ...
[{gen_server,call,3,[{file,"gen_server.erl"},{line,190}]},
  {rabbit_exchange_type_delayed_message,route,2,
      [{file,"src/rabbit_exchange_type_delayed_message.erl"},{line,52}]},
  {rabbit_exchange,route1,3,[]},
  {rabbit_exchange,route,2,[]},
  {rabbit_channel,handle_method,3,[]},
  {rabbit_channel,handle_cast,2,[]},
  {gen_server2,handle_msg,2,[]},
  {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

=WARNING REPORT==== 31-Jan-2016::09:59:00 ===
Non-AMQP exit reason '{{noproc,
                        {gen_server,call,

[{gen_server,call,3,
                         [{file,"gen_server.erl"},{line,190}]},
                        {rabbit_exchange_type_delayed_message,route,2,
                         [{file,
                           "src/rabbit_exchange_type_delayed_message.erl"},
                          {line,52}]},
                        {rabbit_exchange,route1,3,[]},
                        {rabbit_exchange,route,2,[]},
                        {rabbit_channel,handle_method,3,[]},
                        {rabbit_channel,handle_cast,2,[]},
                        {gen_server2,handle_msg,2,[]},
                        {proc_lib,init_p_do_apply,3,
                         [{file,"proc_lib.erl"},{line,237}]}]}'

=INFO REPORT==== 31-Jan-2016::09:59:00 ===
closing AMQP connection <0.24016.59> (127.0.0.1:56710 -> 127.0.0.1:5672)

=INFO REPORT==== 31-Jan-2016::09:59:00 ===
accepting AMQP connection <0.27742.59> (127.0.0.1:38535 -> 127.0.0.1:5672)

Could you help to us?

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users and specify what version of RabbitMQ and the plugin is used.
