### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by martywaz** [rabbitmq/rabbitmq-delayed-message-exchange#39]
Does this still support transactions and publish confirms? Also, if the message cannot be delivered after the delay, is it routed to the designated dead letter queue?

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users. This plugin re-publishes messages to an exchange, and it cannot possible support context-sensitive features such as transactions and publisher confirms: not only it doesn't have any info about the original channel, that channel may be long closed.

**Comment by michaelklishin** [comment]
@martywaz this plugin does not affect routing. There is no such thing as dead letter queues, only [dead letter exchanges](http://rabbitmq.com/dlx.html). Again, this plugin re-publishes messages and does not affect routing performed by "target" exchanges, or how queues work.

**Comment by videlalvaro** [comment]
Although it's written in some sort of broken English, this is partially explained here: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#limitations

**Comment by martywaz** [comment]
ok...so then if the publisher goes out of scope (i.e. no process to receive Returns) .....and the message delivery fails...there's really no way to know that it failed, is that correct?  Were trying to evaluate this as a solution, but we need to be able to handle failures somehow

**Comment by videlalvaro** [comment]
Your best bet would be to use an alternate exchange in case routing fails
