### ISSUE TITLE
Muliple consumers receiving same message when message set with delay using plugin.

### ISSUE THREAD

**Issue by akshay-hazari** [rabbitmq/rabbitmq-delayed-message-exchange#41]
The work queues example (https://www.rabbitmq.com/tutorials/tutorial-two-python.html) works. Only when using the plugin with multiple consumers, all of them receive the same message. 

Link to the stack over flow question :  http://stackoverflow.com/questions/35599425/rabbitmq-multiple-consumers-receiving-same-message-instead-of-round-robin

#!/usr/bin/env python
import pika,cStringIO,pycurl,re,time,logging,traceback,urllib,multiprocessing,sys
from multiprocessing import Pool
from logging.handlers import RotatingFileHandler
from StringIO import StringIO
class cities:
    def __init__(self):
        self.connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
        self.channel = self.connection.channel()
        self.channel.exchange_declare("test-x",type="x-delayed-message",durable=True,auto_delete = False,arguments={"x-delayed-type":"direct"})
        #self.channel.exchange_declare("test-x", "x-delayed-message",True,False)
        #self.channel.exchange_declare("test-x", type="x-delayed-message",False,False,arguments={"x-delayed-type":"direct"})
        
        self.channel.queue_declare(queue='towns_queue',durable=True)
        self.channel.queue_bind(queue="towns_queue", exchange="test-x", routing_key="towns_queue")
        self.logger = logging.getLogger("rabbitmq")
        self.logger.setLevel(logging.DEBUG)
        handler = RotatingFileHandler("logs/Receive.log", maxBytes=100*1024*1024, backupCount=100)
        self.logger.addHandler(handler)
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        handler.setFormatter(formatter)
        self.errlogger = logging.getLogger("Msg_timer_Error")
        self.errlogger.setLevel(logging.ERROR)
        errhandler = RotatingFileHandler("logs/towns_error.log", maxBytes=100*1024*1024, backupCount=100)
        self.errlogger.addHandler(errhandler)
        errformatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        errhandler.setFormatter(errformatter)

    def call_api(self,url):
        do something
        return delay

    def server_log(self,msg,value):
        self.logger.info(msg+" : "+str(value))

    def send_msg(self,msg,delay):
        try:
            delay = delay - 40
            self.server_log("Delay Set : ",delay)
            delay *=1000
            self.channel.basic_publish(exchange='test-x',routing_key='towns_queue',body=msg,properties=pika.BasicProperties(headers={"x-delay":delay},delivery_mode=2,))
            self.server_log("Msg Sent",msg)
        except:
            self.errlogger.exception(msg)
            self.errlogger.exception(str(traceback.print_exc()))
            pass

    def receive(self,ch, method, properties, body):
        try:
            self.server_log("Received message : ",body)
            self.process(body)
            time.sleep(1)
            ch.basic_ack(delivery_tag = method.delivery_tag)
            return body
        except:
            self.errlogger.exception(body)
            self.errlogger.exception(str(traceback.print_exc()))
            pass

    def process(self,body):
        delay=self.call_api(body)
        if delay:
            self.send_msg(body,delay)

    def client(self):
        try:
            self.channel.basic_qos(prefetch_count=1)
            self.channel.basic_consume(self.receive,queue='towns_queue')
            self.channel.start_consuming()
        except:
            self.errlogger.exception(str(traceback.print_exc()))
            pass

    def close(self):
        try:
            self.connection.close()
        except:
            self.errlogger.exception(str(traceback.print_exc()))
            pass

def multiprocess(num_process=4):
    procs = []
    objs = []
    for i in range(4):
        p = multiprocessing.Process(target=cities().client)
        p.start()
        procs.append(p)
    for p in procs:
        p.join()

if __name__ == "__main__":
    if len(sys.argv)> 1:
        num_proc = sys.argv[1]
        if num_proc.isdigit():
            num_proc = int(num_proc)
            multiprocess(num_proc)
        else:
            raise Exception ('num_of_processes needs to be an integer.')
    else:
        multiprocess()

**Comment by michaelklishin** [comment]
Our team does not use issues for questions. Please stop posting the same question everywhere.
