### ISSUE TITLE
Recurring message

### ISSUE THREAD

**Issue by mirkods** [rabbitmq/rabbitmq-delayed-message-exchange#43]
Hi there,
I need to implement this use case: when a message is in the queue it must be requeue each time with the interval defined in the x-delay header.

So my idea is:
- push the message in the queue with the x-delay header (for example 5000)
- when the message goes out from the queue, I nack it so it will be requeued
in this way i can take each message every 5 seconds.

I have problem, when the message is requeued (with the nack operation) seems that the x-delay header is been ignored and the message goes out from the queue immediately, why this behaviour?

I would like to to avoid to ack the message and publish it again.

Mirko

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users.

**Comment by mirkods** [comment]
what is rabbitmq-users?

**Comment by michaelklishin** [comment]
[Right here](https://www.google.ru/webhp?ie=UTF-8#q=Google+rabbitmq-users).

**Comment by mirkods** [comment]
I post this here because it should potentially be a bug

**Comment by michaelklishin** [comment]
@mirkods RabbitMQ does not use GitHub issues for questions or "collective debugging" kind of topics. Issues are for specific actionable items or obvious (to our team) bugs. Everything else belongs to the mailing list.
