### ISSUE TITLE
message cannot be delayed

### ISSUE THREAD

**Issue by JasonHeylon** [rabbitmq/rabbitmq-delayed-message-exchange#44]
I am in OSX 10.11.3, with RabbitMQ 3.5.6, installed rabbitmq_delayed_message_exchange-0.0.1.ez.

I have created a 'x-delayed-message' exchange and bind one queue, publishing message in the management plugin like the image below.
![image](https://cloud.githubusercontent.com/assets/6430692/14010994/8f301edc-f1d5-11e5-8bef-37b153561f50.png)

And the the message will be immediately send to the queue.
![image](https://cloud.githubusercontent.com/assets/6430692/14011041/1d5f1a3c-f1d6-11e5-9dea-f1975738ba15.png)

Is there any wrong things I did?

**Comment by hairyhum** [comment]
`x-delay` header type should be integer, not string. 
Please ask questions in [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users)

**Comment by JasonHeylon** [comment]
@hairyhum  That works, thank you.
