### ISSUE TITLE
Cannot enable plugin

### ISSUE THREAD

**Issue by millencolin99** [rabbitmq/rabbitmq-delayed-message-exchange#45]
I followed the instructions and dropped the plugin .ez file into my /usr/lib/rabbitmq/lib/rabbitmq_server-3.5.3/plugins folder. But when I run the rabbitmq-plugins enable rabbitmq_delayed_message_exchange command it give me an error:

Error: The following plugins could not be found:
  rabbitmq_delayed_message_exchange

**Comment by michaelklishin** [comment]
Please post questions to `rabbitmq-users`. The error message is fairly unambiguous. It could be an `.ez` file permission issue, an issue with incorrect plugins directory location, and so on.
