### ISSUE TITLE
Seeing the number of messages in the exchange

### ISSUE THREAD

**Issue by kovidkapoor** [rabbitmq/rabbitmq-delayed-message-exchange#59]
Hi,

Is there a way I can just get a count of the number of messages that are in the exchange?
Basically, I'm seeing a huge delay in the messages being delivered, and it would be very helpful if I could see this.

Thanks

**Comment by michaelklishin** [comment]
There will be in 3.7.0 (#3). What you are seeing may be what'd been addressed in #54.

**Comment by michaelklishin** [comment]
…and #51, which has the original problem statement.
