### ISSUE TITLE
Is this plugin ready for production ?

### ISSUE THREAD

**Issue by Plasmagun86** [rabbitmq/rabbitmq-delayed-message-exchange#65]
Everything is in the title.

Thanks

**Comment by kjnilsson** [comment]
Please ask questions on the rabbitmq-users mailing list. We use github issues for actionable tasks engineers can work on.

[here](https://groups.google.com/forum/#!searchin/rabbitmq-users/rabbitmq-delayed-message-exchange$20production%7Csort:relevance/rabbitmq-users/sKyhn6SeSi0/aUMgf4plAQAJ) is a link to the last time that question was asked.
