### ISSUE TITLE
Minimum erlang version supported is 18

### ISSUE THREAD

**Issue by suvl** [rabbitmq/rabbitmq-delayed-message-exchange#68]
We had some errors with erlang versions R16B03 and 17.5.3 and this plugin, where the connection to the server would be abruptly terminated.

relevant logs: http://pastebin.com/sf2JMff1

With erlang version 18.3 or greater these errors do not occur.

The stated RabbitMQ supported version is 3.5.7 which states as minimum version R16B03. This plugin should warn about the restrictions on erlang versions.

**Comment by michaelklishin** [comment]
`erlang:system_time/1` is indeed only present in `18.0` and later. However, that function should only be used in the master branch. In any case, I've add a README section in master. RabbitMQ in master already requires Erlang `18.3`.
