### ISSUE TITLE
Mandatory flag not supported?

### ISSUE THREAD

**Issue by nickcash** [rabbitmq/rabbitmq-delayed-message-exchange#7]
Messages published to an x-delayed-message exchange, with an x-delay header and the mandatory flag set, will always get returned as NO_ROUTE... even if they do actually get routed to a queue. This leads to a weird situation where the publisher thinks the message failed, but the consumer receives it anyway.

I'm not sure it's a bug, per se... if the routing isn't actually attempted until after the delay, then I don't know what behavior could be expected. Maybe it should just be documented?

Test case, in case you need it (Python/puka):
```
rabbit = puka.Client("amqp://url-here")
rabbit.wait(rabbit.connect())
rabbit.wait(rabbit.exchange_declare("test-x", 
                                    type="x-delayed-message", 
                                    arguments={"x-delayed-type":"direct"}))
rabbit.wait(rabbit.queue_declare("test-q"))
rabbit.wait(rabbit.queue_bind(queue="test-q", 
                              exchange="test-x", 
                              routing_key="test-q"))

#mandatory=False, OK
rabbit.wait(rabbit.basic_publish(exchange="test-x", 
                                routing_key="test-q", 
                                headers={"x-delay":1000}, 
                                mandatory=False))

#mandatory=True, x-delay=0, OK
rabbit.wait(rabbit.basic_publish(exchange="test-x", 
                                 routing_key="test-q", 
                                 headers={"x-delay":0}, 
                                 mandatory=True))

#mandatory=True, x-delay>0, FAILS
rabbit.wait(rabbit.basic_publish(exchange="test-x", 
                                 routing_key="test-q", 
                                 headers={"x-delay":1}, 
                                 mandatory=True))
```

**Comment by videlalvaro** [comment]
Thanks for the test case, but this is an expected behaviour. I should probably document it on the plugin's README.

The thing is say you publish a message with a delay of 10 seconds and mandatory=true`, and after 5 seconds you close the connection. What does it means to send a routing confirmation later on? Therefore, the plugin doesn't support mandatory.
