### ISSUE TITLE
Delay interval predictability

### ISSUE THREAD

**Issue by brianbarclay** [rabbitmq/rabbitmq-delayed-message-exchange#72]
We have noticed a general issue with the reliability of delayed messages using the x-delay message header and x-delayed-type exchange. Specifically, as the size of the mnesia database grows, delayed messages become gradually more and more delayed.  The delayed message plugin does not respect the delay times in any predictable way.  We have some messages that delay 2000 milliseconds, some that delay 900000 milliseconds (15 minutes), and a variety in between.  We are seeing messages come through the system as much as 3 days after being queued with an x-delay header of 900000   This behavior is similar both inside a 2-node production cluster, and in our test environment which consists of only a single node.   We are able to work around the issue by deleting the mnesia tables, and allowing it to be recreated by the system.

**Comment by michaelklishin** [comment]
To how many rows does it grow?

This plugin is often used as if RabbitMQ was a database. It is not. Beyond a certain number of delayed messages the current design is not going to work and this plugin is not a priority for our team at the moment.

**Comment by michaelklishin** [comment]
Another source of variability is the fact that this plugin relies on Erlang timers. After a certain number of long lived timers in the system they begin to compete for scheduler resources and time drift accumulates.

**Comment by brianbarclay** [comment]
We do not know how many rows, but we believe it gets to be over a million

**Comment by michaelklishin** [comment]
I'd not expect this design to support millions of delayed messages. it wasn't created for heavy duty workloads and should not be used as a secondary (leave alone primary) data store for delayed operations.

One day it may be more suitable for those tasks but not today.

**Comment by brianbarclay** [comment]
Thanks.  we very much appreciate your candor

**Comment by JerryChaox** [comment]
What is the best threshold for production, if I limit the growing of delayed message.

**Comment by lukebakken** [comment]
> What is the best threshold for production, if I limit the growing of delayed message

This depends on your environment. Please ask questions on the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) in the future.

**Comment by lambodar** [comment]
I understood it's not a DB but at the same time there should be options to configure if not a clarification in doc. It'll save lots of time in capital planning. It's a question on integrity of rabbitmq.

**Comment by lambodar** [comment]
I understood it's not a DB but at the same time there should be options to configure if not a clarification in doc. It'll save lots of time in capacity planning. It's a question on integrity of rabbitmq.

**Comment by michaelklishin** [comment]
We plan to re-architect this plugin. Delay predictability may or may not improve meaningfully as a result, it is an open ended question right now. The limitations of this plugin are reasonably extensively documented.

**Comment by rtista** [comment]
So from what I understand, this plugin is not mature enough for heavy usage, does this mean that the previous solution which was described as: 

" use a mix of [message TTL](https://www.rabbitmq.com/docs/ttl#per-message-ttl-in-publishers) and [Dead Letter Exchanges](https://www.rabbitmq.com/docs/dlx) as proposed by James Carr [here](http://blog.james-carr.org/2012/03/30/rabbitmq-sending-a-message-to-be-consumed-later/)." 

Is more suited for production use with heavy load ?

**Comment by michaelklishin** [comment]
@rtista I don't know what "heavy usage" means to you but a combination of TTL and dead-lettering have been used in the community for years, including messaging frameworks such as NServiceBus.
