### ISSUE TITLE
Add binaries to GitHub Releases

### ISSUE THREAD

**Issue by Fydon** [rabbitmq/rabbitmq-delayed-message-exchange#87]
There hasn't been a Bintray release since 14 Sep 2016, however there has been many releases listed on GitHub since then. Could the binary please be included in GitHub Releases?

**Comment by michaelklishin** [comment]
There [weren't any actual code changes](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/commits/stable) since September 2016.

We will see if a new binary build against 3.6.9 is warranted.
