### ISSUE TITLE
delete queued message

### ISSUE THREAD

**Issue by shahbour** [rabbitmq/rabbitmq-delayed-message-exchange#89]
I am planning to use the plugin with our rabbitmq and i was wondering if it is possible to delete or revoke a message after it has been delivered to the exchange .

For example we do send a message that should be delivered after 1 hour , then after 30 min we decided to revoke or delete the message , is this possible by any way or i should do that in my application to ignore any request not needed any more

**Comment by michaelklishin** [comment]
Duplicate of #88.
