### ISSUE TITLE
Build for 3.6.10 fails

### ISSUE THREAD

**Issue by jwoodrich** [rabbitmq/rabbitmq-delayed-message-exchange#95]
I downloaded the source for rabbitmq-delayed-message-exchange-rabbitmq_v3_6_10 (file name rabbitmq_v3_6_10.zip from the releases page for this repository https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases) and tried to build it on a CentOS 7 system with GNU Make 4.2.1, Erlang R20.0, and Elixir 1.5.1.  I'm getting the error:

rc/rabbit_exchange_type_delayed_message.erl:32: undefined callback function info/1 (behaviour 'rabbit_exchange_type')
src/rabbit_exchange_type_delayed_message.erl:32: undefined callback function info/2 (behaviour 'rabbit_exchange_type')

Full output attached.
[build.txt](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/files/1205453/build.txt)

**Comment by jwoodrich** [comment]
I went into the deps directory and checked out the corresponding tags for 3.6.10, found I needed to downgrade Elixir to 1.4.4, and then was able to get it to build.

**Comment by reinaldoborin** [comment]
Do you have the file?
