### ISSUE TITLE
Invest in this plugin

### ISSUE THREAD

**Issue by biiiipy** [rabbitmq/rabbitmq-delayed-message-exchange#97]
Because of severe limitations of this plugins in it's current form - cluster and high message count issues - it's not really usable in production. 
But I would urge team RabbitMQ to reprioritize and invest in this plugin by rewriting it (or incorporating it in core RabbitMQ) so that it fixes the issues, because this plugin can bring **HUGE** value by letting RabbitMQ be used as a Distributed HA Event/Message/Process Scheduler.

**Comment by michaelklishin** [comment]
Thanks for chiming in. We do not use GitHub issues for discussions, please start a rabbitmq-users thread.

FWIW this is one of the more popular community plugins according to the limited download data we have. Which may prove your point but apparently it is good enough for a fair number of users.
